### ISSUE TITLE
AttributeError: 'module' object has no attribute 'spawn'

### ISSUE THREAD

**Issue by kostaz** [pexpect/pexpect#166]
### Issue
---
The most simple example fails to run on Ubuntu 14.04.
The error message is: `AttributeError: 'module' object has no attribute 'spawn'`.

### Setup
---
#### Machine
Ubuntu 14.04 x86_64

#### Installed packages
```
$ dpkg -l | grep pexpect
ii  python-pexpect                                        3.1-1ubuntu0.1                                      all          Python module for automating interactive applications
ii  python3-pexpect                                       3.1-1ubuntu0.1                                      all          Python 3 module for automating interactive applications
```

#### All found pexpect file
```
$ find /usr/lib/python2.7/ /usr/lib/python3/ /usr/lib/python3.4/ /usr/share/hplip/ -type f -iname "*pexpe*.py*" | sort
/usr/lib/python2.7/dist-packages/duplicity/backends/_ssh_pexpect.py
/usr/lib/python2.7/dist-packages/duplicity/backends/_ssh_pexpect.pyc
/usr/lib/python2.7/dist-packages/duplicity/pexpect.py
/usr/lib/python2.7/dist-packages/duplicity/pexpect.pyc
/usr/lib/python2.7/dist-packages/fdpexpect.py
/usr/lib/python2.7/dist-packages/fdpexpect.pyc
/usr/lib/python2.7/dist-packages/pexpect/fdpexpect.py
/usr/lib/python2.7/dist-packages/pexpect/fdpexpect.pyc
/usr/lib/python3/dist-packages/fdpexpect.py
/usr/lib/python3/dist-packages/pexpect/fdpexpect.py
/usr/lib/python3/dist-packages/pexpect/__pycache__/fdpexpect.cpython-34.pyc
/usr/lib/python3/dist-packages/__pycache__/fdpexpect.cpython-34.pyc
/usr/share/hplip/base/pexpect.py
/usr/share/hplip/base/pexpect.pyc
```

#### Source code
```
#!/usr/bin/python3

import pexpect

def main():
    child = pexpect.spawn('ssh root@128.33.22.112')

if __name__ == '__main__':
    main()
```

#### Test log
```
$ ./pexpect.py 
Entered.
Traceback (most recent call last):
  File "./pexpect.py", line 13, in <module>
    main()
  File "./pexpect.py", line 7, in main
    child = pexpect.spawn('ssh root@178.62.18.112')
AttributeError: 'module' object has no attribute 'spawn'
```

Please help to resolve the issue.

**Comment by jquast** [comment]
Thank you for the detailed bug report, @kostaz -- until I can get an Ubuntu VM prepared, could you very simply provide the output of:

```
python3 -c 'import pexpect; print(pexpect.__file__)'
```

```
python2.7 -c 'import pexpect; print(pexpect.__file__)'
```

**Comment by kostaz** [comment]
#### Python3
```
$ python3 -c 'import pexpect; print(pexpect.__file__)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: bad magic number in 'pexpect': b'\x03\xf3\r\n'
```

#### Python2.7
```
$ python2.7 -c 'import pexpect; print(pexpect.__file__)'
pexpect.pyc
```

**Comment by jquast** [comment]
could you try running your program from another folder?

It appears you have a 'pexpect.py' in your local path.

**Comment by kostaz** [comment]
:+1: 

It works ok - see the log below.
Unfortunately, I can't understand what I did wrong during my previous trial...  :-(

I have a strange file `__pycache__/pexpect.cpython-34.pyc` in the previous directory where the error originally happened. It seems this file caused the reported issue. But I don't know how this `.pyc` file got created for no reason...

#### Successful log
```
$ pwd
/tmp/randomdir

$ ls -lsa
total 20
drwxrwxr-x  2 kostaz kostaz  4096 Jan  2 22:05 ./
drwxrwxrwt 12 root   root   12288 Jan  2 22:05 ../
-rwxrwxr-x  1 kostaz kostaz   182 Jan  2 22:06 my_test_pexpect.py*

$ cat my_test_pexpect.py 
#!/usr/bin/python3

import pexpect

def main():
    print("Entered.")
    child = pexpect.spawn('ssh root@192.168.0.1')
    print("Finished.")

if __name__ == '__main__':
    main()

$ ./my_test_pexpect.py 
Entered.
Finished.
```

Thanks for the help anyway.

**Comment by jquast** [comment]
Happy to help.  ``__pycache__/pexpect.cpython-34.pyc`` is the python3 version of python 2's .pyc files.

I think python3 was trying to decode a python2 .pyc file, though I can't say for certain.
