### ISSUE TITLE
p.after can be EOF even when it hasn't thrown EOF

### ISSUE THREAD

**Issue by detly** [pexpect/pexpect#209]
Take this [C code](https://gist.github.com/detly/efc0572bdd08df041c16) (for some reason I could not produce a Python script that shows the same behaviour). Compile it with `gcc -o weirdness weirdness.c`.

Run [this async pexpect script](https://gist.github.com/detly/4005b18705354dd74811). You should get a traceback:

```
Traceback (most recent call last):
  File "./pexpect_eof.py", line 25, in <module>
    main()
  File "./pexpect_eof.py", line 21, in main
    loop.run_until_complete(run())
  File "/usr/lib/python3.4/asyncio/base_events.py", line 208, in run_until_complete
    return future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 243, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 300, in _step
    result = coro.send(value)
  File "./pexpect_eof.py", line 17, in run
    print("1. output: {:s}".format(repr(p.before + p.after)))
TypeError: can't concat bytes to type
```

This is because even in the `else` block, `p.after` is actually the EOF object, and not bytes. I had expected that `p.after` would only ever be data **except** in the `except` block where it's being handled. Is that incorrect? Should callers check for `p.after == pexpect.exceptions.EOF`?

**Comment by detly** [comment]
Incidentally, let's say I try to [account for `p.after`](https://gist.github.com/detly/7ac1a7c1f51e14fc670e) being an EOF exception instead of bytes. I also seem to (a) lose the data I wanted to get in the first place, and (b) get a "Bad file descriptor" traceback:

```
1. output: b'\n'
Traceback (most recent call last):
  File "./pexpect_eof.py", line 33, in <module>
    main()
  File "./pexpect_eof.py", line 29, in main
    loop.run_until_complete(run())
  File "/usr/lib/python3.4/asyncio/base_events.py", line 208, in run_until_complete
    return future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 243, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 300, in _step
    result = coro.send(value)
  File "./pexpect_eof.py", line 12, in run
    _ = yield from p.expect_exact('\r', async=True)
  File "/home/jason/Code/pexpect/pexpect/async.py", line 16, in expect_async
    .connect_read_pipe(lambda: PatternWaiter(expecter), expecter.spawn)
  File "/usr/lib/python3.4/asyncio/base_events.py", line 602, in connect_read_pipe
    transport = self._make_read_pipe_transport(pipe, protocol, waiter)
  File "/usr/lib/python3.4/asyncio/unix_events.py", line 144, in _make_read_pipe_transport
    return _UnixReadPipeTransport(self, pipe, protocol, waiter, extra)
  File "/usr/lib/python3.4/asyncio/unix_events.py", line 258, in __init__
    mode = os.fstat(self._fileno).st_mode
OSError: [Errno 9] Bad file descriptor
```

I'm not really sure what that C code does that the Python script doesn't, except *maybe* just do it faster, which might trip up any timing related issues in the `pexpect` code...?

**Comment by jquast** [comment]
I've tried to make heads or tails of this for a while, it would really help to have a unit test proposed.

I would recommend not to concatenate p.before + p.after unconditionally, and unroll the loop into a "given, exercise, expected" pattern as a test case that fails.  You should be able to execute a and you

also note in a pty, line-terminating character is '\n', from phrase '\r\n', so expecting towards '\r' will always leave trailing '\n'.
