### ISSUE TITLE
pexpect 4.0 does not install with pip or easy_install with python 2.6

### ISSUE THREAD

**Issue by pwrmiller** [pexpect/pexpect#277]
Although Python 2.6 is officially stated as supported (http://pexpect.readthedocs.org/en/stable/install.html), it fails to install when using Python 2.6:

```
Reading http://sourceforge.net/project/showfiles.php?group_id=59762
Best match: pexpect 4.0
Downloading https://pypi.python.org/packages/source/p/pexpect/pexpect-4.0.tar.gz#md5=00dcea09c486f03aa7857cbe2b916085
Processing pexpect-4.0.tar.gz
Running pexpect-4.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-g2APu2/pexpect-4.0/egg-dist-tmp-_k6x_e
Traceback (most recent call last):
  File "/usr/bin/easy_install", line 9, in <module>
    load_entry_point('distribute==0.6.10', 'console_scripts', 'easy_install')()
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 1715, in main
    with_ei_usage(lambda:
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 1696, in with_ei_usage
    return f()
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 1719, in <lambda>
    distclass=DistributionWithoutHelpCommands, **kw
  File "/usr/lib64/python2.6/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.6/distutils/dist.py", line 975, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.6/distutils/dist.py", line 995, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 236, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 472, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 502, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 681, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 958, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 947, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python2.6/site-packages/setuptools/sandbox.py", line 29, in run_setup
    lambda: execfile(
  File "/usr/lib/python2.6/site-packages/setuptools/sandbox.py", line 70, in run
    return func()
  File "/usr/lib/python2.6/site-packages/setuptools/sandbox.py", line 31, in <lambda>
    {'__file__':setup_script, '__name__':'__main__'}
  File "setup.py", line 27
SyntaxError: Non-ASCII character '\xe2' in file setup.py on line 28, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
```
Output from pip:

```
]$ pip install pexpect
/usr/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
You are using pip version 7.1.0, however version 7.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting pexpect
/usr/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading pexpect-4.0.tar.gz (143kB)
    100% |████████████████████████████████| 147kB 957kB/s 
Collecting ptyprocess>=0.5 (from pexpect)
  Downloading ptyprocess-0.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-_eux6G/ptyprocess/setup.py", line 10, in <module>
        "Only python 2.7 and later is supported by ptyprocess.")
    AssertionError: Only python 2.7 and later is supported by ptyprocess.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-_eux6G/ptyprocess
```
ptyprocess apparently requires 2.7: 
https://github.com/pexpect/ptyprocess/blob/master/setup.py states that 2.7 is required.

Can the documentation be updated to reflect that python >= 2.7 is required, or can 2.6 support easily be added?

**Comment by takluyver** [comment]
Sorry, I'd missed updating the docs. Version 4.0 supports 3.3 and later, and 2.7.
