### ISSUE TITLE
Dropped support for python 2.6

### ISSUE THREAD

**Issue by david-caro** [pexpect/pexpect#293]
Even though the package still has the python 2.6 category in pip, it's not longer installable there because it depends on ptyprocess>=0.5 and that does not support anymore python<2.7:
```
sh-4.1# pip install pexpect
Collecting pexpect
  Downloading pexpect-4.0.1.tar.gz (143kB)
    100% |████████████████████████████████| 147kB 750kB/s 
Collecting ptyprocess>=0.5 (from pexpect)
  Downloading ptyprocess-0.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-WELumL/ptyprocess/setup.py", line 10, in <module>
        "Only python 2.7 and later is supported by ptyprocess.")
    AssertionError: Only python 2.7 and later is supported by ptyprocess.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-WELumL/ptyprocess
```

**Comment by takluyver** [comment]
Thanks, I had missed the trove classifiers.
