### ISSUE TITLE
WIP asyncio, transport __del__ causes spawn.close() early

### ISSUE THREAD

**Issue by jquast** [pexpect/pexpect#294]
When ``asyncio.get_event_loop().set_debug(True)`` is called, dangling references prevent the special ``__del__`` method, attached in unix_transports.py to be called. When False (default), __del__ is called much later, probably on interpreter close.

https://github.com/python/asyncio/blob/master/asyncio/unix_events.py#L375

As an effect, the ``spawn.close`` method is called multiple times per ``child`` instance long before ``EOF`` is reached! Exactly, the number of ``expect_``-family of method calls with ``async=True`` called until that time.

For example code,
```
    yield from child.expect("telnet> ", async=True)
    child.sendline(u"set options")
    yield from child.expect(u"telnet> ", async=True)
    child.sendline(u"open {0} {1}".format(bind_host, unused_tcp_port))
    yield from child.expect_exact("Trying {0}...\r\n".format(bind_host), async=True)
    yield from child.expect_exact("test-telsh % ", async=True)
    yield from child.expect(pexpect.EOF, async=True)
```

The following is logged:

```
--------------------------------- Captured log ---------------------------------
160.89 DEBUG selector_events.py:53 Using selector: KqueueSelector
161.71 DEBUG selector_events.py:53 Using selector: KqueueSelector
166.23 INFO test_bsdtelnet.py:35 Listening on ('127.0.0.1', 53341)
174.84 DEBUG async.py:55 data_received b'telnet> '
175.46 DEBUG async.py:55 data_received b'Will show option processing.\r\n'
175.57 DEBUG async.py:55 data_received b'telnet> '
185.80 DEBUG async.py:55 data_received b'Trying 127.0.0.1...\r\n'
188.11 WARNING unix_events.py:377 unclosed transport <_UnixReadPipeTransport fd=17 idle>
188.11 WARNING unix_events.py:377 unclosed transport <_UnixReadPipeTransport fd=17 idle>
213.75 DEBUG pty_spawn.py:317 caller_module=/Users/docker/.virtualenvs/telnetlib3/lib/python3.5/site-packages/asyncio/unix_events.py:378
213.83 DEBUG pty_spawn.py:318 close: force=True
318.43 DEBUG pty_spawn.py:676 isalive? True
318.67 WARNING unix_events.py:377 unclosed transport <_UnixReadPipeTransport fd=17 idle>
318.82 WARNING unix_events.py:377 unclosed transport <_UnixReadPipeTransport fd=17 idle>
```

As an effect of the pipe.close method called in __del__, and mixing with asyncio callbacks, results vary! However, we can see many **symptomatic** effects of ``child_fd`` being set ``-1`` in close method in callbacks:

```
        # await connection banner,
        yield from child.expect_exact("Trying {0}...\r\n".format(bind_host),
                                      timeout=5,
>                                     async=True)

telnetlib3/tests/test_bsdtelnet.py:56:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../pexpect/pexpect/async.py:28: in expect_async
    return expecter.timeout(e)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <pexpect.expect.Expecter object at 0x10b12a198>, err = TimeoutError()

    def timeout(self, err=None):
        spawn = self.spawn
        from . import TIMEOUT

        spawn.before = spawn.buffer
        spawn.after = TIMEOUT
        index = self.searcher.timeout_index
        if index >= 0:
            spawn.match = TIMEOUT
            spawn.match_index = index
            return index
        else:
            spawn.match = None
            spawn.match_index = None
            msg = str(spawn)
            if err is not None:
                msg = str(err) + '\n' + msg
>           raise TIMEOUT(msg)
E           pexpect.exceptions.TIMEOUT:
E           <pexpect.pty_spawn.spawn object at 0x10b0b2ef0>
E           command: /usr/bin/telnet
E           args: [b'/usr/bin/telnet']
E           searcher: None
E           buffer (last 100 chars): ''
E           before (last 100 chars): ''
E           after: <class 'pexpect.exceptions.TIMEOUT'>
E           match: None
E           match_index: None
E           exitstatus: None
E           flag_eof: False
E           pid: 56884
E           child_fd: -1
E           closed: True
E           timeout: 1
E           delimiter: <class 'pexpect.exceptions.EOF'>
E           logfile: None
E           logfile_read: None
E           logfile_send: None
E           maxread: 65534
E           ignorecase: False
E           searchwindowsize: 1024
E           delaybeforesend: 0.0
E           delayafterclose: 0.0
E           delayafterterminate: 0.0

../pexpect/pexpect/expect.py:68: TIMEOUT
--------------------------------- Captured log ---------------------------------
154.32 DEBUG selector_events.py:53 Using selector: KqueueSelector
154.89 DEBUG selector_events.py:53 Using selector: KqueueSelector
158.87 INFO test_bsdtelnet.py:35 Listening on ('127.0.0.1', 53430)
167.26 ERROR async.py:55 data_received b'telnet> '
168.09 ERROR async.py:55 data_received b'Will show option processing.\r\n'
168.25 ERROR async.py:55 data_received b'telnet> '
168.83 WARNING unix_events.py:377 unclosed transport <_UnixReadPipeTransport fd=17 idle>
193.28 ERROR pty_spawn.py:317 caller_module=/Users/docker/.virtualenvs/telnetlib3/lib/python3.5/site-packages/asyncio/unix_events.py:378
193.37 ERROR pty_spawn.py:318 close: force=True
295.24 ERROR pty_spawn.py:676 isalive? True
295.48 WARNING unix_events.py:377 unclosed transport <_UnixReadPipeTransport fd=17 idle>
296.02 ERROR base_events.py:1008 Exception in callback BaseSelectorEventLoop.add_reader(17, <bound method...d=17 polling>>)
handle: <Handle BaseSelectorEventLoop.add_reader(17, <bound method...d=17 polling>>)>
Traceback (most recent call last):
  File "/Users/docker/.virtualenvs/telnetlib3/lib/python3.5/site-packages/asyncio/selector_events.py", line 234, in add_reader
    key = self._selector.get_key(fd)
  File "/Users/docker/.virtualenvs/telnetlib3/lib/python3.5/site-packages/asyncio/selectors.py", line 182, in get_key
    raise KeyError("{!r} is not registered".format(fileobj)) from None
KeyError: '17 is not registered'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/docker/.virtualenvs/telnetlib3/lib/python3.5/site-packages/asyncio/events.py", line 120, in _run
    self._callback(*self._args)
  File "/Users/docker/.virtualenvs/telnetlib3/lib/python3.5/site-packages/asyncio/selector_events.py", line 237, in add_reader
    (handle, None))
  File "/Users/docker/.virtualenvs/telnetlib3/lib/python3.5/site-packages/asyncio/selectors.py", line 527, in register
    self._kqueue.control([kev], 0, 0)
OSError: [Errno 9] Bad file descriptor
300.06 DEBUG telsh.py:92 shell stream: pause_writing
300.71 INFO server.py:190 Connection from 127.0.0.1:53431
300.80 DEBUG server.py:717 env_update: {'REMOTE_IP': '127.0.0.1', 'REMOTE_PORT': '53431', 'REMOTE_HOST': '127.0.0.1'}
300.99 DEBUG telsh.py:113 queued output:
test-telsh %
301.06 DEBUG telopt.py:511 send IAC GA
301.75 DEBUG server.py:717 env_update: {'HOSTNAME': 'docker.local'}
301.90 DEBUG telopt.py:1990 pending_option[DO + TTYPE] = True
301.97 DEBUG telopt.py:498 send IAC DO TTYPE
302.33 INFO server.py:676  using  disconnected from 127.0.0.1:53431 (localhost) after 0.0s (0s idle): [Errno 32] Broken pipe
302.52 DEBUG server.py:717 env_update: {'REMOTE_IP': '127.0.0.1', 'REMOTE_PORT': '53431', 'REMOTE_HOST': 'localhost'}
302.62 DEBUG server.py:760 server getfqdn canceled
302.68 DEBUG server.py:371 telopt negotiation canceled
!!!!!!!!!!!!!!!!!!!! Interrupted: stopping after 1 failures !!!!!!!!!!!!!!!!!!!!

```

**Comment by takluyver** [comment]
That's annoying. I see two possible ways around it:

1. Cache the PatternWaiter (and by extension, the transport) on the spawn instance from the first `expect(... async=True)` call, and reuse it on each async expect call. So the transport would live as long as the spawn instance. This was one of the things I experimented with for solving #213 (I think it worked, but the solution I found in #288 was nicer)
2. Instead of passing asyncio the `spawn` instance, pass it a wrapper whose `fileno()` returns the same thing but whose `close()` is a no-op. Then the transport can be closed without closing the underlying pty.

**Comment by jquast** [comment]
Will any solution accommodate constructing multiple expect waiters? It is allowed (no error), but I'm not sure to expect good behavior:

```python
done, pending = asyncio.wait([
    child.expect(['some phrase', pexpect.EOF], async=True),
    child.expect(['something else ...', pexpect.TIMEOUT, async=True),
    [something else ...], timeout=3)
```

Also its very strange that asyncio expect call provides timeout argument in duplication to asyncio framework. I think the asyncio's is so much more preferred over "timeout is index 4, check return value" pattern :)

**Comment by takluyver** [comment]
Neither of those solutions, nor the present behaviour, allows multiple simultaneous expect calls on the *same* child. It won't error, but I don't think it will do anything useful. It would take some fairly major reworking to make it workable, and I don't see any advantage over putting the patterns to match in a single expect call.

I'm not quite sure what you mean about timeouts. Matching TIMEOUT as a pattern is certainly an odd API, but I wanted the async interface to match the normal blocking pexpect interface.
