### ISSUE TITLE
"Timeout exceeded" when using replwrap

### ISSUE THREAD

**Issue by ajmazurie** [pexpect/pexpect#305]
Hi,
I had success in the past using `pexpect` to bring a BASH terminal-like interface in a Jupyter notebook. Today however I'm having a "Timeout exceeded" error when doing so and I'm not sure what is causing the problem. The simplest code reproducing this error on my machine is as follows:

```python
Python 2.7.10 (default, Sep 28 2015, 20:58:10) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.72)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pexpect.replwrap
>>> pexpect.replwrap.bash()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ajmazurie/.pyenv/versions/jupyter/lib/python2.7/site-packages/pexpect/replwrap.py", line 113, in bash
    extra_init_cmd="export PAGER=cat")
  File "/Users/ajmazurie/.pyenv/versions/jupyter/lib/python2.7/site-packages/pexpect/replwrap.py", line 51, in __init__
    prompt_change.format(new_prompt, continuation_prompt))
  File "/Users/ajmazurie/.pyenv/versions/jupyter/lib/python2.7/site-packages/pexpect/replwrap.py", line 61, in set_prompt
    self.child.expect(orig_prompt)
  File "/Users/ajmazurie/.pyenv/versions/jupyter/lib/python2.7/site-packages/pexpect/spawnbase.py", line 315, in expect
    timeout, searchwindowsize, async)
  File "/Users/ajmazurie/.pyenv/versions/jupyter/lib/python2.7/site-packages/pexpect/spawnbase.py", line 339, in expect_list
    return exp.expect_loop(timeout)
  File "/Users/ajmazurie/.pyenv/versions/jupyter/lib/python2.7/site-packages/pexpect/expect.py", line 104, in expect_loop
    return self.timeout(e)
  File "/Users/ajmazurie/.pyenv/versions/jupyter/lib/python2.7/site-packages/pexpect/expect.py", line 68, in timeout
    raise TIMEOUT(msg)
pexpect.exceptions.TIMEOUT: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0x10548e890>
command: /bin/bash
args: ['/bin/bash', '--rcfile', '/Users/ajmazurie/.pyenv/versions/jupyter/lib/python2.7/site-packages/pexpect/bashrc.sh']
searcher: None
buffer (last 100 chars): u'\x1b[?1034h(jupyter)%{\x1b[33m%}Indigo %B%{\x1b[33m%}%30<...<%~%b %{\x1b[36m%}%% %{\x1b[00m%}'
before (last 100 chars): u'\x1b[?1034h(jupyter)%{\x1b[33m%}Indigo %B%{\x1b[33m%}%30<...<%~%b %{\x1b[36m%}%% %{\x1b[00m%}'
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 95592
child_fd: 5
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
>>> 
```

Note that there is no such file `'/Users/ajmazurie/.pyenv/versions/jupyter/lib/python2.7/site-packages/pexpect/bashrc.sh`; not sure if that is relevant.

Best,
Aurelien

**Comment by takluyver** [comment]
That is quite probably relevant, I think we forgot to specify `package_data`. One moment...

**Comment by takluyver** [comment]
Can you try installing from PR #306?
