### ISSUE TITLE
Failure on Travis

### ISSUE THREAD

**Issue by takluyver** [pexpect/pexpect#393]
I guess something in Travis' infrastructure has changed, leading to this in one of the diagnostic tools run before the real tests:

```
Traceback (most recent call last):
  File "./tools/display-terminalinfo.py", line 209, in <module>
    main()
  File "./tools/display-terminalinfo.py", line 204, in main
    print('os.ttyname({0}) => {1}'.format(fd, os.ttyname(fd)))
OSError: [Errno 0] Error
```

**Comment by takluyver** [comment]
Fixed in 29d97fc4b49aba0d772f067b7b453a220f52db0b
