### ISSUE TITLE
pexpect "Bad file descriptor" issue when using the pty_spawn.pyc file

### ISSUE THREAD

**Issue by ksvasan** [pexpect/pexpect#400]
Error sending password to host: <hostname>, error=[Errno 9] Bad file descriptor
Traceback (most recent call last):
  File "./mssh", line 204, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "./mssh", line 195, in main
    host2status = await process_batch(coro_list)
  File "./mssh", line 161, in process_batch
    host, child, result = await gen_coro(host, child, True)
  File "./mssh", line 137, in coro_wrapper
    result = await coro
  File "/usr/local/lib/python3.5/dist-packages/pexpect/async.py", line 17, in expect_async
    .connect_read_pipe(lambda: PatternWaiter(expecter), expecter.spawn)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 986, in connect_read_pipe
    transport = self._make_read_pipe_transport(pipe, protocol, waiter)
  File "/usr/lib/python3.5/asyncio/unix_events.py", line 169, in _make_read_pipe_transport
    return _UnixReadPipeTransport(self, pipe, protocol, waiter, extra)
  File "/usr/lib/python3.5/asyncio/unix_events.py", line 308, in __init__
    mode = os.fstat(self._fileno).st_mode
OSError: [Errno 9] Bad file descriptor

But this scenario actually works without issues when I touch the pty_spawn.py file (i.e.) make the modification date to be the current date (so that the pty_spawn.pyc file is unused during compilation).

Once I revert the modification time of pty_spawn.py to the one in pty_spawn.pyc file the error actually appears again any clue why this could happen? Any known bug in the older compilers?

mssh is the script that I'm writing to automate multiple ssh logins.

Additional Info:
This seems to be a clear case of -1 being returned for the file descriptor in asyncio module (_UnixReadPipeTransport.__init__ -> mode = os.fstat(self._fileno).st_mode) which uses the pipe.fileno() to get the underlying FD (implemented in SpawnBase.py inherited by pty_spawn.py)

**Comment by takluyver** [comment]
It's possible sometimes to get stale `.pyc` files, so there's a change in the `.py` file which is not being used because it imports the `.pyc`. Normally, touching the `.py` file and re-running it is enough to regenerate the `.pyc` file, but if you're not running as root, you can't modify files in `/usr`.

Have you tried uninstalling all copies of pexpect and installing it again?

**Comment by ksvasan** [comment]
I had tried that (simply deleted the pexpect folder in /usr/local/lib/python3.5/dist-packages/pexpect) to no avail. Anyway I've a work around to use for now so not too bothered but wanted to ensure that this is not due some compiler over optimization 👍

**Comment by takluyver** [comment]
I don't think it can be - Python only does a few compiler optimisations, and I can't think how any of them would affect this:

- Constant folding, i.e. `2 + 3` becomes `5` at compile time.
- Remove docstrings (optional)
- Remove `assert` statements (optional).

**Comment by bkhouri** [comment]
> I've a work around to use for now 
@ksvasan  mind sharing your workaround if you recall what it was?  I'm encountering the same issue `OSError: [Errno 9] Bad file descriptor` when calling `pexpect.spawn()` and I'm not sure how to fix it.

**Comment by brandonrwin** [comment]
> I'm encountering the same issue `OSError: [Errno 9] Bad file descriptor` when calling `pexpect.spawn()` and I'm not sure how to fix it.

I just ran into this. It was happening if I ran the code inside of pytest, in the setup_method of a test class. If I move it out of there, it works. My naive assumption is that pytest is doing some funny business to capture output.

**Comment by pmcharrison** [comment]
See also this PyCharm bug report: https://youtrack.jetbrains.com/issue/PY-60474
