### ISSUE TITLE
pexpect.exceptions.TIMEOUT: Timeout exceeded

### ISSUE THREAD

**Issue by ManjuAnnure** [pexpect/pexpect#403]
Traceback (most recent call last):
  File "config.py", line 28, in <module>
    child.expect(pexpect.EOF, timeout=10)
  File "/usr/local/lib/python2.7/dist-packages/pexpect/spawnbase.py", line 321, in expect
    timeout, searchwindowsize, async)
  File "/usr/local/lib/python2.7/dist-packages/pexpect/spawnbase.py", line 345, in expect_list
    return exp.expect_loop(timeout)
  File "/usr/local/lib/python2.7/dist-packages/pexpect/expect.py", line 107, in expect_loop
    return self.timeout(e)
  File "/usr/local/lib/python2.7/dist-packages/pexpect/expect.py", line 70, in timeout
    raise TIMEOUT(msg)
pexpect.exceptions.TIMEOUT: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0xb71d460c>
command: /usr/bin/vtysh
args: ['/usr/bin/vtysh']
buffer (last 100 chars): '       Net Link States (Area 0.0.0.1)\r\n\r\nLink ID         ADV Router      Age  Seq#       CkSum\r\n:\x1b[K'
before (last 100 chars): '       Net Link States (Area 0.0.0.1)\r\n\r\nLink ID         ADV Router      Age  Seq#       CkSum\r\n:\x1b[K'
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 9298
child_fd: 6
closed: False
timeout: 1
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: <open file 'show.txt', mode 'w' at 0xb72415a0>
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: EOF

**Comment by takluyver** [comment]
That looks like the expected result of it timing out before finding EOF. If you think there's a bug, you'll have to explain in a bit more detail why.

**Comment by ManjuAnnure** [comment]
1st script 👍 
Able to see output but its hitting traceback .
The line "child.expect(pexpect.EOF, timeout=10)"  i introduced for  verification.

2nd script:
when i merge to 1st script unable to execute 2nd script.

**Comment by champagne** [comment]
Seem not get the expected EOF, but get TIMEOUT, why not child.expect([pexpect.EOF, pexpect.TIMEOUT], timeout=10) ?

**Comment by jnatschev** [comment]
without knowing what you were doing it is difficult to say.

however, i can only assume that your previous code line was a child.send() or child.sendline() and your child.expect() isn’t expecting a regular expression or string so even though there is probably output as a result of the child.send()/child.sendline(), you’re not expecting it; only an eof or timeout and timeout is being hit. eof will only be hit if the spawned session (ssh for example) was terminated.

**Comment by akufon** [comment]
Hello, could you share if and how this error was resolved? I am running into similar error currently when I run a python script.
