### ISSUE TITLE
Preserve terminal size

### ISSUE THREAD

**Issue by singalen** [pexpect/pexpect#413]
`child.interact()`, when child is `ssh`, doesn't preserve the current terminal size. 
Probably has something to do with a pseudo-terminal that `interact()` creates.
A reference: http://unix.stackexchange.com/questions/207782/how-are-terminal-length-and-width-forwarded-over-ssh-and-telnet

Probably the pexpect or the program using it should handle `SIGWINCH`.

**Comment by super1-chen** [comment]
I met the same problem as you, but I wrote a function which can detect the window's size before starting the child spawn
I do that below:
`        def terminal_size():
            h, w, hp, wp = struct.unpack('HHHH',
                                         fcntl.ioctl(0, termios.TIOCGWINSZ,
                                                     struct.pack('HHHH', 0, 0,
                                                                 0, 0)))
            return h, w`

then I set height and width to the child spawn before it's interacting
like
 `
default_rows, default_columns = terminal_size()，
p = pexpect.spawn('ssh %(ssh_user)s@%(ssh_host)s -p %(ssh_port)s' % {
            'ssh_user': ssh_user, 'ssh_host': ssh_host, 'ssh_port': ssh_port})
p.setwinsize(default_rows, default_columns)
`
thanks

**Comment by singalen** [comment]
Thanks for sharing!
I also did a workaround, but the point is that this can be fixed on pexpect level.

My (much slower) code, for reference:

```
def get_term_size():
    """
    horrible non-portable hack to get the terminal size to transmit
    to the child process spawned by pexpect
    """
    (rows, cols) = os.popen("stty size").read().split() # works on Mac OS X, YMMV
    rows = int(rows)
    cols = int(cols)
    return (rows, cols)
```

**Comment by teddyjoe** [comment]
Sorry to post this query here, I am very much new to python and wexpect. I am trying to import and use python WExpect module as is to connect from my windows machine(running windows 7) to linux server. while doing it , I am getting a following error.
ExceptionPexpect :The command was not found or was not executable: ssh root@192.00.00.00.
basically I want to connect to that server ip using wexpect and the start interacting with it .
Can anyone please help me on it.
I running my python script from my windows environment(CMD)

Actual error message is below
--------------------------------
Traceback (most recent call last):
File "D:\Toyota-Brazil\WorkProducts\pytomy\frameui.py", line 5, in 
cmd = spawn('ssh root@192.00.00.00')
File "D:\Toyota-Brazil\WorkProducts\pytomy\wexpect.py", line 144, in spawn
return spawn_windows(command, args, timeout, maxread, searchwindowsize, logfile, cwd, env)
File "D:\Toyota-Brazil\WorkProducts\pytomy\wexpect.py", line 1411, in init
self._spawn (command, args)
File "D:\Toyota-Brazil\WorkProducts\pytomy\wexpect.py", line 1456, in _spawn
raise ExceptionPexpect ('The command was not found or was not executable: %s.' % self.command)
ExceptionPexpect: The command was not found or was not executable: ssh root@192.00.00.00.

The module I tried to use is following: https://gist.github.com/anthonyeden/8488763
Can anyone help me one this?

**Comment by takluyver** [comment]
wexpect is a separate project from pexpect, so sorry, I can't help with that.

**Comment by Red-M** [comment]
To answer the original issue,
```
s = pxssh.pxssh()
s.setwinsize(default_rows, default_columns)
```
Will let you the option to set the terminal size before you connect to an SSH server.

**Comment by singalen** [comment]
I already do the workaround, but I'll have to watch window resizes in my code.
The point if the issue is that this can be fixed on pexpect level.

**Comment by Red-M** [comment]
I'd recommend before you call `child.interact()` and you know you're dealing with `ssh` or other commands that don't handle terminal size correctly, that you set the terminal size using `.setwinsize(default_rows, default_columns)` on the pexpect or pxssh object and retrieving the terminal size however you wish to obtain them.

**Comment by singalen** [comment]
Waht do you mean "`ssh` doesn't handle terminal size correctly"?
I just ssh-ed into another machine, ran `mc`, resized local terminal window, and `mc` responded. This means ssh does handle terminal size correctly.

**Comment by keeely** [comment]
As @singalen points out, this could be fixed at the pexpect level.  I don't quite understand why the documentation has a code sample for handling windows resize.  How about just adding a class to handle both the initial sizing and re-sizing (and avoid the use of the global with a callable and revert the signal handler when done).  Something like:

```
class TerminalSizer:
    def __init__(self, process):
        self.process = process

    def get_size(self):
        """Return tuple with rows, columns"""
        s = struct.pack("HHHH", 0, 0, 0, 0)
        a = struct.unpack('hhhh', fcntl.ioctl(sys.stdout.fileno(), termios.TIOCGWINSZ, s))
        return a[0], a[1]

    def __enter__(self):
        self.process.setwinsize(*self.get_size())
        signal.signal(signal.SIGWINCH, self)
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        signal.signal(signal.SIGWINCH, signal.SIG_DFL)

    def __call__(self, sig, data):
        if not self.process.closed:
            self.process.setwinsize(*self.get_size())


with TerminalSizer(child)
   child.interact()
```
