### ISSUE TITLE
pexpect.popen_spawn.PopenSpawn(ssh commend) didn't work on windows

### ISSUE THREAD

**Issue by whtis** [pexpect/pexpect#414]
hello,
I am trying to use pexpect to Login SSH automatically on `windows10`.The python version is `3.5.2` and pexpect is `4.2.1`.
```
import traceback
import pexpect
from pexpect.popen_spawn import PopenSpawn

try:
    child = pexpect.popen_spawn.PopenSpawn('ssh root@192.168.21.225')
    a = child.expect(['password:', 'The authenticity of host'], timeout=300, async=True)
    if a == 0:
        child.sendline('123456789')
        print('this ip has exists in know_host files!')
    if a == 1:
        print('this ip will be added to know_host files!')
        child.sendline('yes')
        child.expect('password:')
        child.sendline('123456789')
        # send test
        child.sendline("df -h")
        child.interact()
except pexpect.EOF:
    traceback.print_exc()
```
because cmd can not use `ssh` I use the [`cmder`](https://github.com/cmderdev/cmder) instead. The `python` or `ssh` can work well if I typed artificial. But when I run the code in `cmder` like this:
`python ssh.py`

I got the error below and I can't find more information via google.

```
Traceback (most recent call last):
  File "C:\develop_tools\Python3\lib\site-packages\pexpect\expect.py", line 99, in expect_loop
    incoming = spawn.read_nonblocking(spawn.maxread, timeout)
  File "C:\develop_tools\Python3\lib\site-packages\pexpect\popen_spawn.py", line 66, in read_nonblocking
    raise EOF('End Of File (EOF).')
pexpect.exceptions.EOF: End Of File (EOF).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ssh.py", line 7, in <module>
    a = child.expect(['password:', 'The authenticity of host'])
  File "C:\develop_tools\Python3\lib\site-packages\pexpect\spawnbase.py", line 321, in expect
    timeout, searchwindowsize, async)
  File "C:\develop_tools\Python3\lib\site-packages\pexpect\spawnbase.py", line 345, in expect_list
    return exp.expect_loop(timeout)
  File "C:\develop_tools\Python3\lib\site-packages\pexpect\expect.py", line 105, in expect_loop
    return self.eof(e)
  File "C:\develop_tools\Python3\lib\site-packages\pexpect\expect.py", line 50, in eof
    raise EOF(msg)
pexpect.exceptions.EOF: End Of File (EOF).
<pexpect.popen_spawn.PopenSpawn object at 0x00000238FC1F1550>
searcher: searcher_re:
    0: re.compile("b'password:'")
    1: re.compile("b'The authenticity of host'")
```

Another question is, it seems `pexpect.popen_spawn.PopenSpawn` doesn't have `interact()` method to turn over control to the user, so how can I do sth if the code can work?

**Comment by Cjesse** [comment]
I also ran into this problem, did you fix it? and how?

**Comment by whtis** [comment]
@Cjesse not yet. I use another way to run this script and it can work on windows.this is my way:
firstly，install `Bash on Windows`  [like this](https://msdn.microsoft.com/zh-cn/commandline/wsl/install_guide)

you should change the sentence:
```python
//child = pexpect.popen_spawn.PopenSpawn('ssh root@192.168.21.225')
child = pexpect.spawn('ssh root@192.168.21.225')
```

and then, enter the `linux` to run the script. 
The only problem is,  if we login ssh via the way above, we can't edit the file by vim correctly.

**Comment by teddyjoe** [comment]
Sorry to post this query here, I am very much new to python and wexpect. I am trying to import and use python WExpect module as is to connect from my windows machine(running windows 7) to linux server. while doing it , I am getting a following error.
ExceptionPexpect :The command was not found or was not executable: ssh root@192.00.00.00.
basically I want to connect to that server ip using wexpect and the start interacting with it .
Can anyone please help me on it.
I running my python script from my windows environment(CMD)

Actual error message is below
Traceback (most recent call last):
File "D:\Toyota-Brazil\WorkProducts\pytomy\frameui.py", line 5, in
cmd = spawn('ssh root@192.00.00.00')
File "D:\Toyota-Brazil\WorkProducts\pytomy\wexpect.py", line 144, in spawn
return spawn_windows(command, args, timeout, maxread, searchwindowsize, logfile, cwd, env)
File "D:\Toyota-Brazil\WorkProducts\pytomy\wexpect.py", line 1411, in init
self._spawn (command, args)
File "D:\Toyota-Brazil\WorkProducts\pytomy\wexpect.py", line 1456, in _spawn
raise ExceptionPexpect ('The command was not found or was not executable: %s.' % self.command)
ExceptionPexpect: The command was not found or was not executable: ssh root@192.00.00.00.

The module I tried to use is following: https://gist.github.com/anthonyeden/8488763
Can anyone help me one this?

**Comment by vthach** [comment]
For remote execution from windows system to UNIX hosts I've used paramiko.  Remote execution from UNIX-to-UNIXish system, pexpect works well for me.   To use pexpect on Windows system I had to do it in Cygwin.   There are modules like secureconfig that is not easy to install on Windows system without compiling from source, which Cygwin makes very easy to do.

**Comment by takluyver** [comment]
If you're happy to work with paramiko directly, I would recommend that over using pexpect. Paramiko is using the SSH protocol directly, whereas pexpect is driving a virtual terminal on your local machine and running `ssh` inside that. Although the virtual terminal approach is more similar to using ssh interactively, it's a whole extra layer of stuff to go wrong.

**Comment by ymkim92** [comment]
I had lots of problem in using pexpect in Windows. From the takluyver's advice, I tried to use paramiko and found paramiko-expect. It was a package I looked for.

**Comment by carloscartola** [comment]
Hi all, another solution that will work for using pxssh on Windows is installing a Unix environment with Cygwin (http://cygwin.com/). Then you will have a shell and all Unix-like tools installed on it and if you install python inside it, this python can install pexpect with a working pxssh. I have just tested and executed a successful ssh section starting from a Windows to a Unix machine.
