### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'read'

### ISSUE THREAD

**Issue by PureWhiteWu** [pexpect/pexpect#426]
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pexpect/popen_spawn.py", line 97, in _read_incoming
    buf = os.read(fileno, 1024)
AttributeError: 'NoneType' object has no attribute 'read'
```

**Comment by takluyver** [comment]
You can get weird errors in threads when Python is shutting down. You may simply ignore them if they don't matter to you, or you can ensure that threads finish cleanly before your program exits.
