### ISSUE TITLE
why pexpect hangs on the sendline?

### ISSUE THREAD

**Issue by peasentspring** [pexpect/pexpect#435]
I use pexpect to interacitve with a program, i set the logfile = stdout. because the interactive is large, so when the size of the logfile is 657242 bytes, the output is stop. But the python script doesn't stop. And when I send a SIGINT signal to the python thread, the terminal output is 
`Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "verify_pg.py", line 178, in run
    self.check_firstlevel(self.pgd_dst, self.pgd_src)
  File "verify_pg.py", line 159, in check_firstlevel
    flag = self.check_secondlevel(pgd_dst_value, pgd_src_value)
  File "verify_pg.py", line 122, in check_secondlevel
    flag = self.check_thirdlevel(pud_dst_value, pud_src_value)
  File "verify_pg.py", line 74, in check_thirdlevel
    self.p.sendline("rd -p %s" % pmd_src)
  File "/usr/local/lib/python2.7/dist-packages/pexpect/pty_spawn.py", line 535, in sendline
    return self.send(s + self.linesep)
  File "/usr/local/lib/python2.7/dist-packages/pexpect/pty_spawn.py", line 526, in send
    return os.write(self.child_fd, b)
OSError: [Errno 4] Interrupted system call

Traceback (most recent call last):
  File "verify_pg.py", line 224, in <module>
    main()
  File "verify_pg.py", line 204, in main
    tidgroup[index].join()
  File "/usr/lib/python2.7/threading.py", line 940, in join
    self.__block.wait()
  File "/usr/lib/python2.7/threading.py", line 340, in wait
    waiter.acquire()
KeyboardInterrupt
`

**Comment by abhishek-ak** [comment]
Hi were you able to get the solution. Even i am getting similar error

I am sending a command _child.sendline('[some command]')_ which is failing
` File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pexpect/pty_spawn.py", line 535, in sendline
    return self.send(s + self.linesep)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pexpect/pty_spawn.py", line 526, in send
    return os.write(self.child_fd, b)
OSError: [Errno 9] Bad file descriptor`
