### ISSUE TITLE
Windows: pexpect.spawn not working

### ISSUE THREAD

**Issue by Nemish1** [pexpect/pexpect#439]
Any alternative for pexpect.spawn for windows? 
Have been trying out `pexpect.popen_spawn.PopenSpawn` and `pexpect.fdpexpect.fdspawn` instead, as suggested in [http://pexpect.readthedocs.io/en/stable/overview.html#pexpect-on-windows](url) but it is not working.

**Comment by donfiguerres** [comment]
Hi @Nemish1 , can you elaborate please? It would be helpful if you present a use case or code sample here.
I tried it in my box and it is working fine. Please see sample below.
    Python 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:14:34) [MSC v.1900 32 bit (Intel)] on win32
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import os, sys, io, pexpect, pexpect.popen_spawn
    >>> child = pexpect.popen_spawn.PopenSpawn("echo Hello World!")
    >>> child.wait()
    0
    >>> child.read()
    b'Hello World!\n'
    >>>

**Comment by teddyjoe** [comment]
I am very much new to python and wexpect. I am trying to import and use python WExpect module as is to connect from my windows machine to linux server. while doing it , I am getting a following error.
ExceptionPexpect :The command was not found or was not executable: ssh root@192.00.00.00.
basically I want to connect to that server ip using wexpect and the start interacting with it .
Can anyone please help me on it.
I running my python script from my windows environment(CMD)

Actual error message is below
Traceback (most recent call last):
  File "D:\Toyota-Brazil\WorkProducts\pytomy\frameui.py", line 5, in <module>
    cmd = spawn('ssh root@192.00.00.00')
  File "D:\Toyota-Brazil\WorkProducts\pytomy\wexpect.py", line 144, in spawn
    return spawn_windows(command, args, timeout, maxread, searchwindowsize, logfile, cwd, env)
  File "D:\Toyota-Brazil\WorkProducts\pytomy\wexpect.py", line 1411, in __init__
    self._spawn (command, args)
  File "D:\Toyota-Brazil\WorkProducts\pytomy\wexpect.py", line 1456, in _spawn
    raise ExceptionPexpect ('The command was not found or was not executable: %s.' % self.command)
ExceptionPexpect: The command was not found or was not executable: ssh root@192.00.00.00.

Can anyone help me one this?

**Comment by amroczeK** [comment]
As @donfiguerres stated, you are probably haven't imported it properly, try:

import pexpect.popen_spawn

**Comment by doc808** [comment]
I used paramiko and paramiko_expect to make the ssh connection to get around this error. For example:

import paramiko
from paramiko_expect import SSHClientInteraction


def session(ip, username, password):
    ssh = paramiko.SSHClient()
    ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    ssh.connect(ip, username=username, password=password)
    interact = SSHClientInteraction(ssh, timeout=60, display=True)  

    interact.expect('Router#') 
    interact.send('show ip route')

**Comment by raczben** [comment]
Try [wexpect](https://github.com/raczben/wexpect), which is the windows alternative of pexpect. Wexpect emulates pseudo-terminal on Windows.

```python
import wexpect 

child = wexpect.spawn('cmd.exe')
child.expect('>')
child.sendline('ls')
child.expect('>')
print(child.before)
child.sendline('exit')
```

**Comment by nprasadnurani** [comment]
I was able to create one exe with wexpect. Download the wexpect from github. follow the instruction to build it and then follow the below link to create one exe file instead of two exe
https://github.com/raczben/wexpect/wiki/Wexpect-with-pyinstaller#how-to-use-wexpect-with-pyinstaller
https://github.com/raczben/wexpect/issues/12#issuecomment-605390122
