### ISSUE TITLE
Syntax error in pexpect/spawnbase.py: async is a reserved keyword in Python 3.7+

### ISSUE THREAD

**Issue by ogrisel** [pexpect/pexpect#453]
Here the traceback I got when starting ipython on the current Python master.

```python
Traceback (most recent call last):
  File "/home/ogrisel/.virtualenvs/py37/bin/ipython", line 7, in <module>
    from IPython import start_ipython
  File "/home/ogrisel/.virtualenvs/py37/lib/python3.7/site-packages/IPython/__init__.py", line 54, in <module>
    from .core.application import Application
  File "/home/ogrisel/.virtualenvs/py37/lib/python3.7/site-packages/IPython/core/application.py", line 25, in <module>
    from IPython.core import release, crashhandler
  File "/home/ogrisel/.virtualenvs/py37/lib/python3.7/site-packages/IPython/core/crashhandler.py", line 27, in <module>
    from IPython.core import ultratb
  File "/home/ogrisel/.virtualenvs/py37/lib/python3.7/site-packages/IPython/core/ultratb.py", line 120, in <module>
    from IPython.utils import path as util_path
  File "/home/ogrisel/.virtualenvs/py37/lib/python3.7/site-packages/IPython/utils/path.py", line 17, in <module>
    from IPython.utils.process import system
  File "/home/ogrisel/.virtualenvs/py37/lib/python3.7/site-packages/IPython/utils/process.py", line 18, in <module>
    from ._process_posix import system, getoutput, arg_split, check_pid
  File "/home/ogrisel/.virtualenvs/py37/lib/python3.7/site-packages/IPython/utils/_process_posix.py", line 23, in <module>
    import pexpect
  File "/home/ogrisel/.virtualenvs/py37/lib/python3.7/site-packages/pexpect/__init__.py", line 75, in <module>
    from .pty_spawn import spawn, spawnu
  File "/home/ogrisel/.virtualenvs/py37/lib/python3.7/site-packages/pexpect/pty_spawn.py", line 14, in <module>
    from .spawnbase import SpawnBase
  File "/home/ogrisel/.virtualenvs/py37/lib/python3.7/site-packages/pexpect/spawnbase.py", line 224
    def expect(self, pattern, timeout=-1, searchwindowsize=-1, async=False):
                                                                   ^
SyntaxError: invalid syntax
```

pexpect version: 4.2.1

**Comment by ogrisel** [comment]
Apparently, this is already fixed in master in f668f7f39662586306d853049c5fe96125209cb8.

**Comment by takluyver** [comment]
This is a good reminder to make a new release with the fix, though.

**Comment by ogrisel** [comment]
Cross-linking to #450 that I did not find by keyword searching github issues.

**Comment by takluyver** [comment]
Released 4.3.

**Comment by black-snow** [comment]
Manually upgrading pexpect fixed it for me, thanks.

**Comment by ianmiell** [comment]
Is this version not available as a pip? I have to install from source to resolve.

**Comment by elfelround** [comment]
upgrading pexpect fixed it for me too. was getting this error when using

jupyter nbconvert --to html

```
def expect(self, pattern, timeout=-1, searchwindowsize=-1, async=False):
SyntaxError: invalid syntax
```
