### ISSUE TITLE
pexpect.exceptions.ExceptionPexpect: Could not terminate the child

### ISSUE THREAD

**Issue by gson1703** [pexpect/pexpect#462]
I am using pexpect as part of the automated test infrastructure for
the NetBSD project, running various emulators (qemu, gxemul),
virtual machine monitors (Xen xm), and even scripts controlling
physical machines through a serial console as children of pexpect.

Sometimes, while attempting to shut down the system under test,
I get an exception "pexpect.exceptions.ExceptionPexpect: Could not
terminate the child".  It looks like this is caused by not just
one, but several issues with pexpect:

1. The default delayafterclose and delayafterterminate settings of 0.1
seconds are just too short.  They might work fine with toy examples,
but when the child process is large, or needs to do things like
flushing and closing a physical serial port on exit, it can easily
take longer than 0.1 seconds to die.

2. Even though the delayafterclose and delayafterterminate settings
are essential due to (1), they do not appear to be documented.

3. In pexpect 3.0, you could work around (1) by setting
child.delayafterclose and child.delayafterterminate to a sufficiently
large value, and this worked both for child.close() and
child.terminate().  In 4.3.1, the code for killing child processes is
duplicated between ptyprocess.py (PtyProcess.terminate()) and
pty_spawn.py (spawn.terminate()), and which one is used depends on
whether you call child.close() or child.terminate().  Furthermore,
they are controlled by separate variables, so if you want both
child.close() and child.terminate() to work reliably, you need to set
four (!) different variables:

  child.delayafterclose
  child.delayafterterminate
  child.ptyproc.delayafterclose
  child.ptyproc.delayafterterminate

Coming up with a minimal test case to demonstrate the problem is a bit
tricky because small test programs tend to take less than 0.1 seconds
to die.  The best I could come up with is the following, where the
child deliberately dumps core on SIGHUP; this reproduces the issue on
machines where core dumps are enabled and dumping core is sufficiently
slow.

```
$ cat dumpy.c
#include <stdio.h>
#include <signal.h>
#include <stdlib.h>
#include <unistd.h>
#include <memory.h>
void handler(int sig) {
    size_t size = 1000000000;
    char *p = malloc(size);
    memset(p, 0xff, size);
    abort();
}
int main(int argc, char **argv) {
    signal(SIGHUP, handler);
    signal(SIGINT, handler);
    printf("hello\n");
    sleep(60);
    return 0;
}
$ cat test.py
import pexpect
child = pexpect.spawn('./dumpy')
child.expect("hello")
child.close()
$ cc dumpy.c -o dumpy
$ ulimit -c unlimited
$ python2.7 test.py
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    child.close()
  File "/usr/lib/python2.7/dist-packages/pexpect/pty_spawn.py", line 318, in close
    self.ptyproc.close(force=force)
  File "/usr/lib/python2.7/dist-packages/ptyprocess/ptyprocess.py", line 391, in close
    raise PtyProcessError('Could not terminate the child.')
ptyprocess.ptyprocess.PtyProcessError: Could not terminate the child.
$
```

My criterion for considering this bug fixed would be that either the
above test runs reliably without throwing an exception, or it can at
least be made to do so using a documented setting.

**Comment by jcaplan** [comment]
I was bumping into the same issue today. What I noticed is that `delayafterclose` is never used anymore, and now `delayafterterminate` can be set once, I don't think there's any duplication anymore. so just setting `spawn.delayafterterminate`resolved my issue.

It would still be nice if this was documented.
