### ISSUE TITLE
Python3: Error when using interact() with encoding=utf-8, logfile=sys.stdout

### ISSUE THREAD

**Issue by jheidbrink** [pexpect/pexpect#506]
## pexpect Version

4.6.0

## Python version

3.6.5

## Error description

The following ipython session raises an Exception:
```
In [29]: c = pexpect.spawn('bash', encoding='utf-8', logfile=sys.stdout)

In [30]: c.interact()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-30-7f2803c6d69b> in <module>()
----> 1 c.interact()

/usr/lib/python3.6/site-packages/pexpect/pty_spawn.py in interact(self, escape_character, input_filter, output_filter)
    764             escape_character = escape_character.encode('latin-1')
    765         try:
--> 766             self.__interact_copy(escape_character, input_filter, output_filter)
    767         finally:
    768             tty.tcsetattr(self.STDIN_FILENO, tty.TCSAFLUSH, mode)

/usr/lib/python3.6/site-packages/pexpect/pty_spawn.py in __interact_copy(self, escape_character, input_filter, output_filter)
    809                 if output_filter:
    810                     data = output_filter(data)
--> 811                 self._log(data, 'read')
    812                 os.write(self.STDOUT_FILENO, data)
    813             if self.STDIN_FILENO in r:

/usr/lib/python3.6/site-packages/pexpect/spawnbase.py in _log(self, s, direction)
    124     def _log(self, s, direction):
    125         if self.logfile is not None:
--> 126             self.logfile.write(s)
    127             self.logfile.flush()
    128         second_log = self.logfile_send if (direction=='send') else self.logfile_read

TypeError: write() argument must be str, not bytes
```

**Comment by jpic** [comment]
pexpect implemented workaround for writing to stdout in the method defined above, but not for logfile.

Patch proposal in #539
Released in pexpect-py3-patch pypi module if you need meanwhile

**Comment by mh5** [comment]
For some reasons I don't understand, I'm getting this error specifically when I run my script in ConEmu, but not when I run it in mintty. Basically, I invoke a Python function from a Python shell and the function SSH logins to some server (through a jumpserver, in case that's relevant). Once I'm over SSH, the issue occurs when I do some specific key combinations. For example, if I press the up  arrow to get the previous command from history, press the left arrow a couple of times, and then try to add a space, then I'm thrown back to the Python terminal with that error.

```
  File "<stdin>", line 1, in <module>
  File "<string>", line 197, in sh
  File "/usr/lib/python3.6/site-packages/pexpect/pty_spawn.py", line 766, in interact
    self.__interact_copy(escape_character, input_filter, output_filter)
  File "/usr/lib/python3.6/site-packages/pexpect/pty_spawn.py", line 812, in __interact_copy
    os.write(self.STDOUT_FILENO, data)
OSError: [Errno 14] Bad address
```

And if I try to interact again, then I get back to where I was over SSH, so the session is not destroyed.

I'm not really familiar with the code base of pexpect and I'm not sure if this may have side effects, but I just have the issue resolved when I update pty_spawn.py by replacing

```
os.write(self.STDOUT_FILENO, data)
```

with

```
try:                                  
    os.write(self.STDOUT_FILENO, data)
except OSError:                       
    pass
```

Is there a better way I should handle this?
