### ISSUE TITLE
'spawn' object has no attribute 'pexpect'

### ISSUE THREAD

**Issue by yangxj99** [pexpect/pexpect#511]
centos 7.2
python 2.7 
/usr/lib/python2.7/site-packages/pexpect
pexpect 4.6.0
#### test.py
#!/usr/bin/python

import pexpect

def send_comm(child, cmd):
    child.sendline(cmd)
    child.expect(Promt)

def connect(user, host, password):
    connStr = 'ssh ' + user + '@' + host
    child = pexpect.spawn(connStr)
    result = child.pexpect([pexpect.TIMEOUT, 'password:'])
    if result == 0:
        print "[-] Error"
        return
    elif result == 1:
        child.sendline(password)
    child.expect(Promt)
    return child

def main():
    host = '192.168.xx.xx'
    user = 'root'
    password = '*************'
    child = connect(user,host,password)
    send_command(child, 'w')

if __name__ == '__main__':
    main()
######### issue problem ###
Traceback (most recent call last):
  File "ss.py", line 30, in <module>
    main()
  File "ss.py", line 26, in main
    child = connect(user,host,password)
  File "ss.py", line 13, in connect
    result = child.pexpect([pexpect.TIMEOUT, 'password:'])
AttributeError: 'spawn' object has no attribute 'pexpect'

any ideas ? thinks

**Comment by jnatschev** [comment]
try child.expext() instead of child.pexpext()
