### ISSUE TITLE
pexpect.spawn() can hang when environment variables contain Unicode characters (or integers/floats)

### ISSUE THREAD

**Issue by ryanpetrello** [pexpect/pexpect#512]
```python
~ python
>>> import pexpect
>>> pexpect.spawn(
...     'sleep', ['1'], cwd='/tmp/', env={'FOO': u'Iñtërnâtiônàlizætiøn'}, ignore_sighup=True,
...     encoding='utf-8', echo=False
... )

# <python hangs>
```

From time to time, I've found that `pexpect.spawn()` **hangs**.  I've debugged further with `gdb` and found that it's stuck here:

```python
(gdb) py-bt
#4 Frame 0x3a2eab0, for file /venv/xyz/lib/python2.7/site-packages/ptyprocess/ptyprocess.py, line 300, in spawn (cls=<type at remote 0x2d3e950>, argv=[...], cwd='...', env={...}
    exec_err_data = os.read(exec_err_pipe_read, 4096)
#9 Frame 0x3a5c6a0, for file /venv/xyz/lib/python2.7/site-packages/pexpect/pty_spawn.py, line 314, in _spawnpty (self=<spawn(softspace=False, _encoder=<IncrementalEncoder(buffer='', errors='strict') at remote 0x7f106514dc90>, ...(truncated)
    return ptyprocess.PtyProcess.spawn(args, **kwargs)
#14 Frame 0x3a5b8c0, for file /venv/xyz/lib/python2.7/site-packages/pexpect/pty_spawn.py, line 303, in _spawn (self=<spawn(softspace=False, _encoder=<IncrementalEncoder(buffer='', errors='strict') at remote 0x7f106514dc90>, ...(truncated)
    cwd=self.cwd, **kwargs)
#18 Frame 0x3a49bf0, for file /venv/xyz/lib/python2.7/site-packages/pexpect/pty_spawn.py, line 204, in __init__ (self=<spawn(softspace=False, _encoder=<IncrementalEncoder(buffer='', errors='strict') at remote 0x7f106514dc90>, ...(truncated)
    self._spawn(command, args, preexec_fn, dimensions)
---Type <return> to continue, or q <return> to quit---
```

This seems to happen if you have environment variables that contain unicode; in this scenario, it's possible for `os.execvpe` to raise `UnicodeEncodeError` (which is uncaught by `ptyprocess`):

```python
# python test.py
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    os.execvpe('sleep', ['1'], env={'FOO': u'Iñtërnâtiônàlizætiøn'})
  File "/venv/xyz/lib64/python2.7/os.py", line 353, in execvpe
    _execvpe(file, args, env)
  File "/venv/xyz/lib64/python2.7/os.py", line 380, in _execvpe
    func(fullname, *argrest)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf1' in position 1: ordinal not in range(128)
```

https://github.com/pexpect/ptyprocess/blob/master/ptyprocess/ptyprocess.py#L286 doesn't seem particularly robust to failures like this (it only catches `OSError`).  This results in a scenario where the child process doesn't write its failure back on the pipe, and the parent just reads forever on the other end.

**Comment by ryanpetrello** [comment]
This seems to happen if you have environment variables that contain unicode:

```python
# python test.py
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    os.execvpe('sleep', ['1'], env={'FOO': u'Iñtërnâtiônàlizætiøn'})
  File "/venv/awx/lib64/python2.7/os.py", line 353, in execvpe
    _execvpe(file, args, env)
  File "/venv/awx/lib64/python2.7/os.py", line 380, in _execvpe
    func(fullname, *argrest)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf1' in position 1: ordinal not in range(128)
```

https://github.com/pexpect/ptyprocess/blob/master/ptyprocess/ptyprocess.py#L285 doesn't seem particularly robust to failures like this.

**Comment by ryanpetrello** [comment]
@takluyver you have any opinions about the best way to handle this?  Enforcing `utf-8` on environment variables is a quick fix:

```python
+            for k, v in env.items():
+                env[k] = v.encode('utf-8')
```

...but I'm not sure if that's kosher across platforms.

**Comment by ryanpetrello** [comment]
@takluyver https://github.com/pexpect/ptyprocess/pull/47

**Comment by ryanpetrello** [comment]
This also affects env vars that are integers/floats, because the `os.execvpe` call raises an uncaught `TypeError` on fork:

```
~ python
>>> import pexpect
>>> pexpect.spawn(
...     'sleep', ['1'], cwd='/tmp/', env={'FOO': 1}, ignore_sighup=True,
...     encoding='utf-8', echo=False
... )

# <python hangs>
```
