### ISSUE TITLE
intermittent UnicodeEncodeError when writing log file

### ISSUE THREAD

**Issue by nitroamos** [pexpect/pexpect#516]
Hi Pexpect devs,

I recently started using `pexpect` to be able to interact with a command line tool, and it works very well. However, in my testing, I'm seeing that maybe 1 in 50 times I'm getting the exception I've pasted below. That is, it's not reproducible. I've pasted a simplified version of the business logic of my code below.

```
   cmd = "gmx pdb2gmx -v -ter -o gromacs.pdb -p gromacs.top -ignh -water tip3p -ff charmm27 -f "+preprocessed
   p = pexpect.spawn(cmd,encoding="UTF-8",logfile=open("pdb2gmx.log",'w'))

   error = False
   while p.isalive():
      try:
         idx = p.expect(["Fatal error:",
                         "Select (start|end) terminus type for ([\w\-\d]*)\r\n(.+None\s*\r\n)"])

         print(p.before)
         print(p.after)

         if idx == 0:
            error = True
            break
         # snip
         p.sendline(selectedOption)

      except pexpect.EOF:
         print(p.before)
      except pexpect.TIMEOUT:
         print("\nTIMEOUT")
         print(p.before)
   p.expect(pexpect.EOF)
   print(p.before)
   p.close()
```

```
Traceback (most recent call last):
  File "utils.py", line 893, in makeGromacs
    "Select (start|end) terminus type for ([\w\-\d]*)\r\n(.+None\s*\r\n)"])
  File "myAnaconda/lib/python3.6/site-packages/pexpect/spawnbase.py", line 341, in expect
    timeout, searchwindowsize, async_)
  File "myAnaconda/lib/python3.6/site-packages/pexpect/spawnbase.py", line 369, in expect_list
    return exp.expect_loop(timeout)
  File "myAnaconda/lib/python3.6/site-packages/pexpect/expect.py", line 111, in expect_loop
    incoming = spawn.read_nonblocking(spawn.maxread, timeout)
  File "myAnaconda/lib/python3.6/site-packages/pexpect/pty_spawn.py", line 485, in read_nonblocking
    return super(spawn, self).read_nonblocking(size)
  File "myAnaconda/lib/python3.6/site-packages/pexpect/spawnbase.py", line 179, in read_nonblocking
    self._log(s, 'read')
  File "myAnaconda/lib/python3.6/site-packages/pexpect/spawnbase.py", line 126, in _log
    self.logfile.write(s)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 359: ordinal not in range(128)
```

I'm not sure how easy it would be to enable one of you to reproduce this, but maybe I won't bother if it's not necessary. Anyway, the exception seems to indicate a logic error, but the way it's occurring makes it seem like a race condition.

Is there anything wrong with what I'm doing?

**Comment by takluyver** [comment]
When you `open()` the log file, try explicitly telling it to use `encoding="UTF-8"` for the file as well.
