### ISSUE TITLE
Receive bytes intead of str in `output_filter` under unicode encoding.

### ISSUE THREAD

**Issue by giovanism** [pexpect/pexpect#517]
Based on this doc, I wrote my output_filter to match certain patterns.

> You may pass in optional input and output filter functions. These
> functions should take a string and return a string. The output_filter
> will be passed all the output from the child process. The input_filter
> will be passed all the keyboard input from the user. The input_filter
> is run BEFORE the check for the escape_character.

But this is not the case when I run it under python3.

I have to wrap around my output_filter using something like:
```
def output_filter_utf8(out_raw):
    return output_filter(out_raw.decode('utf-8')).encode('utf-8')
```

It doesn't matter whether I pass `encoding='utf-8'` or not to `spawn`.

My error message:
```
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/giovanism/Repos/garbage/pys/tsudo/tsudo/__main__.py", line 4, in <module>
    tsudo.main(sys.argv[1:])
  File "/home/giovanism/Repos/garbage/pys/tsudo/tsudo/tsudo.py", line 15, in main
    sudo.interact(output_filter=insults_filter)
  File "/home/giovanism/.local/lib/python3.6/site-packages/pexpect/pty_spawn.py", line 766, in interact
    self.__interact_copy(escape_character, input_filter, output_filter)
  File "/home/giovanism/.local/lib/python3.6/site-packages/pexpect/pty_spawn.py", line 810, in __interact_copy
    data = output_filter(data)
  File "/home/giovanism/Repos/garbage/pys/tsudo/tsudo/tsudo.py", line 21, in insults_filter
    if sudo_out == '\r\n' or attempts_up_pat.match(sudo_out):
TypeError: cannot use a string pattern on a bytes-like object
```

**Comment by takluyver** [comment]
The doc probably hasn't changed since Python 3 support was added. Do you want to update it to say talk about bytes rather than strings?
