### ISSUE TITLE
Pexpect is not printing the show command output as expected.

### ISSUE THREAD

**Issue by deepak844** [pexpect/pexpect#518]
I write the below script to enter into router & put show IP int brief command & want that output however getting None output.
=========================================
Import pexpect
Import re
Import sys 
Import time

c = pexpect.spawn('telnet 10.3.0.20')
c.logfile = sys.stdout
print ("Trying to open .....10.3.0.20")
c.expect = (''Username: )
c.sendline = ('xxxxxx')
print ("Now you are in user mode")
p.expect = ('>')
c.sendline = ('en')
p.expect = ('Password: ')
c.sendline = ('cisco')
print ("Now you are in enable mode")
c.expect = ('#')
c.sendline = ('show ip int brief')
time.sleep(5)
c.expect = ('#')
print "<<<<<<<<....output...>>>>"
print c.before
c.close

==============================================
Below is my Output:
=====================
root@kali:#python test1.py
Trying to open .....10.3.0.20
Now you are in user mode
Now you are in enable mode
<<<<<<<<....output...>>>>
None
root@kali:#

=======================

**Comment by jnatschev** [comment]
for your expect, try the following as a regular expression to match your prompt:
‘\r\n[\x21-\x7E]+#$’

The only thing that i can see is that c.expect(‘#’) is not behaving as you are “expecting” to (yes, a bit of a pun).



Cheers,
John Natschev

**Comment by MoonStruckHorrors** [comment]
@deepak844 

First of all, the way that you're using `expect` and `sendline` is incorrect. These are functions - NOT variables. This is not right.

````
c.expect = (''Username: )
c.sendline = ('xxxxxx')
````

Do it like this:

````
c.expect(''Username: )
c.sendline('xxxxxx')
````

Secondly, you're doing `expect('#')` which would find the first occurance of `#` (since the last successful expect).  You could do something like this: https://gist.github.com/MoonStruckHorrors/4500896c57c3c73e92a3bde439e402f7

Also, for debugging put some `c.before`s and see what's happening.

**Comment by deepak844** [comment]
Hi Nikhil ,
Thanks  for your suggestion however still no luck for me.

===========================================================================================
Now I write a new code for the following setup.

Linux machine ====>>Linux jump server(RSA authentication)=====>>Device(to get show output)
=============================================================================================
#!/usr/bin/python

import sys
import pexpect
import time
import re

passcode = raw_input("Enter Passcode:")
k = pexpect.spawn('ssh kumard31@158.87.22.201')
k.logfile=sys.stdout
k.expect('Enter PASSCODE:')
k.sendline(passcode)
k.expect('Password:')
k.sendline('Matlab@1234%^&*()!')
print(".....ssh Jump session is getting open.....")
k.expect('$')
ssh_newkey = 'Are you sure you want to continue connecting'
# my ssh command line
k.sendline('ssh kumard31@10.27.61.135')
try:
    	i=k.expect([ssh_newkey,'Password:'])
        if i==0:
                k.sendline('yes')
        if i==1:
                k.sendline('Matlab@1234%^&*()!')
except  EOF:
	print "I either got key or connection timeout"
        pass


k.expect('#')
print("<<<<<Now you are in router mode..Enjoy>>>>>")
sys.stdout = open("output.txt","w")
k.sendline('terminal length 0' + '\r\n')
k.sendline('sh interface brief ')
time.sleep(5)

k.expect('{#}$')

router_output = k.before
print router_output

sys.stdout.close()
k.close()
===========================================================================================================
I have enabled logging for this code & I got bebow logging events. and nothing captured in output.txt file.
===========================================================================================================
[deepak@oc6681421563 ~]$ python sshnew.py
Enter Passcode:38302164
Enter PASSCODE:38302164

Password: Matlab@1234%^&*()!
.....ssh Jump session is getting open.....

ssh kumard31@10.27.61.135
ssh kumard31@10.27.61.135
Last login: Tue Aug  7 02:26:25 2018 from 9.79.201.125
[kumard31@a0001p5rjmp0002 ~]$ ssh kumard31@10.27.61.135


Password: Matlab@1234%^&*()!

Bad terminal type: "xterm-256color". Will assume vt100.
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (c) 2002-2016, Cisco Systems, Inc. All rights reserved.
The copyrights to certain works contained in this software are
owned by other third parties and used and distributed under
license. Certain components of this software are licensed under
the GNU General Public License (GPL) version 2.0 or the GNU
Lesser General Public License (LGPL) Version 2.1. A copy of each
such license is available at
http://www.opensource.org/licenses/gpl-2.0.php and
http://www.opensource.org/licenses/lgpl-2.1.php
l123713c5548s2004.san2# <<<<<Now you are in router mode..Enjoy>>>>>
terminal length 0

sh interface brief 
terminal length 0

l123713c5548s2004.san2# 
l123713c5548s2004.san2# 
l123713c5548s2004.san2# sh interface brief 

--------------------------------------------------------------------------------
Ethernet      VLAN    Type Mode   Status  Reason                   Speed     Port
Interface                                                                    Ch #
--------------------------------------------------------------------------------
Eth1/1        1       eth  trunk  up      none                        10G(D) --
Eth1/2        1       eth  trunk  up      none                        10G(D) --
Eth1/3        1       eth  trunk  up      none                        10G(D) --
Eth1/4        1       eth  trunk  up      none                        10G(D) --
Eth1/5        1       eth  trunk  up      none                        10G(D) --
Eth1/6        1       eth  trunk  up      none                        10G(D) --
Eth1/7        1       eth  trunk  up      none                        10G(D) --
Eth1/8        1       eth  trunk  up      none                        10G(D) --
Eth1/9        1       eth  access down    SFP not inserted            10G(D) --
Eth1/10       311     eth  access up      none                        10G(D) --
Eth1/11       311     eth  access up      none                        10G(D) --
Eth1/12       311     eth  access up      none                        10G(D) --
Eth1/13       321     eth  access up      none                        10G(D) --
Eth1/14       321     eth  access up      none                        10G(D) --
Eth1/15       1       eth  access down    SFP not inserted            10G(D) --
Eth1/16       1       eth  f-path up      none                        10G(D) 100
Eth1/17       1       eth  f-path up      none                        10G(D) 100
Eth1/18       2022    eth  access up      none                        10G(D) --
Eth1/19       1       eth  access down    SFP not inserted            10G(D) --
Eth1/20       1       eth  f-path up      none                        10G(D) --
Eth1/21       1       eth  f-path up      none                        10G(D) --
Eth1/22       1       eth  access down    SFP not inserted            10G(D) --
Eth1/23       1       eth  access down    SFP not inserted            10G(D) --
Eth1/24       1       eth  access down    SFP not inserted            10G(D) --
Eth1/25       811     eth  access up      none                        10G(D) --
Eth1/26       811     eth  access up      none                        10G(D) --
Eth1/27       811     eth  access up      none                        10G(D) --
Eth1/28       831     eth  access up      none                        10G(D) --
Eth1/29       831     eth  access up      none                        10G(D) --
Eth1/30       1       eth  access down    SFP not inserted            10G(D) --
Eth1/31       1       eth  access down    SFP not inserted            10G(D) --
Eth1/32       1       eth  access down    SFP not inserted            10G(D) --

--------------------------------------------------------------------------------
Port-channel VLAN    Type Mode   Status  Reason                    Speed   Protocol
Interface                                                                  
--------------------------------------------------------------------------------
Po100        1       eth  f-path up      none                       a-10G(D)  lacp

--------------------------------------------------------------------------------
Port   VRF          Status IP Address                              Speed    MTU
--------------------------------------------------------------------------------
mgmt0  --           up     10.27.61.135                            1000     1500

-------------------------------------------------------------------------------
Interface Secondary VLAN(Type)                    Status Reason                 
-------------------------------------------------------------------------------
Vlan1     --                                      down   Administratively down  
Vlan2022  --                                      up     --        
l123713c5548s2004.san2# Traceback (most recent call last):
  File "sshnew.py", line 39, in <module>
    k.expect('{#}$')
  File "/usr/lib/python2.7/site-packages/pexpect.py", line 1311, in expect
    return self.expect_list(compiled_pattern_list, timeout, searchwindowsize)
  File "/usr/lib/python2.7/site-packages/pexpect.py", line 1325, in expect_list
    return self.expect_loop(searcher_re(pattern_list), timeout, searchwindowsize)
  File "/usr/lib/python2.7/site-packages/pexpect.py", line 1409, in expect_loop
    raise TIMEOUT (str(e) + '\n' + str(self))
pexpect.TIMEOUT: Timeout exceeded in read_nonblocking().
<pexpect.spawn object at 0x7fb64c49abd0>
version: 2.3 ($Revision: 399 $)
command: /usr/bin/ssh
args: ['/usr/bin/ssh', 'kumard31@158.87.22.201']
searcher: searcher_re:
    0: re.compile("{#}$")
buffer (last 100 chars): wn  
Vlan2022  --                                      up     --        
l123713c5548s2004.san2# 
before (last 100 chars): wn  
Vlan2022  --                                      up     --        
l123713c5548s2004.san2# 
after: <class 'pexpect.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 23332
child_fd: 3
closed: False
timeout: 30
delimiter: <class 'pexpect.EOF'>
logfile: <open file '<stdout>', mode 'w' at 0x7fb64c5df150>
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
[deepak@oc6681421563 ~]$

===========================================================================================

**Comment by slel** [comment]
@deepak844 please surround code fragments by triple backquotes.

For example, type this:

    ```
    # this is a code fragment

    Import pexpect

    c = pexpect.spawn('telnet 10.3.0.20')
    ```

which will then display as:

> ```
> # this is a code fragment
> 
> Import pexpect
> 
> c = pexpect.spawn('telnet 10.3.0.20')
> ```

whereas without triple backquotes it is interpreted as markdown and displays as

> # this is a code fragment
>
> Import pexpect
>
> c = pexpect.spawn('telnet 10.3.0.20')

**Comment by deepak844** [comment]
HI Nikhil ,

Can you give me the code for my issue.
thanks much.

Deepak

**Comment by MoonStruckHorrors** [comment]
Nope.

**Comment by zartaz** [comment]
try this 
change 'k.logfile=sys.stdout'  to  'k.logfile = sys.stdout.buffer' in your code
