### ISSUE TITLE
run_command throws a TypeError exception when passed bytes

### ISSUE THREAD

**Issue by ericshawlinux** [pexpect/pexpect#531]
Currently sending bytes to REPLWrapper causes a TypeError exception. I think that it should accept bytes.

```python
#!/usr/bin/python3
from pexpect.replwrap import REPLWrapper
py = REPLWrapper("python3", ">>> ", None)
py.run_command(b'\x34\x2b\x37')
```
```Python traceback
Traceback (most recent call last):
  File "./test.py", line 6, in <module>
    py.run_command(b'\x34\x2b\x37')
  File "/usr/lib/python3/dist-packages/pexpect/replwrap.py", line 82, in run_command
    if command.endswith('\n'):
TypeError: endswith first arg must be bytes or a tuple of bytes, not str
```

**Comment by ericshawlinux** [comment]
I'm going to attempt to fix this and open a pull request.
