### ISSUE TITLE
How should i use 'expect' in windows?

### ISSUE THREAD

**Issue by neverxie** [pexpect/pexpect#533]
Hi all:
i use PopenSpawn in win10, that's ok.
but i use child.expect(' \ | /'), 
    box.expect('msh')
  File "C:\Python27\lib\site-packages\pexpect\spawnbase.py",line 341, in expect
    timeout,searchwindowsize,async_)
  File "C:\Python27\lib\site-packages\pexpect\spawnbase.py", line 369, in expect_list
    return exp.expect_loop(timeout)
  File "C:\Python27\lib\site-packages\pexpect\expect.py", line 117, in expect_loop
    return self.eof(e)
  File "C:\Python27\lib\site-packages\pexpect\expect.py", line 63, in eof
    raise EOF(msg)

P.S. expect is ok in linux

**Comment by neverxie** [comment]
`Traceback (most recent call last):
  File ".\run.py", line 37, in <module>
    box = qemubox.BoxStartup()
  File "E:\GitHub\neverxie\git\rt-thread\bsp\qemu-vexpress-a9\te\qemubox.py", line 51, in BoxStartup
    child.expect('msh')
  File "C:\Python27\lib\site-packages\pexpect\spawnbase.py", line 341, in expect
    timeout, searchwindowsize, async_)
  File "C:\Python27\lib\site-packages\pexpect\spawnbase.py", line 369, in expect_list
    return exp.expect_loop(timeout)
  File "C:\Python27\lib\site-packages\pexpect\expect.py", line 117, in expect_loop
    return self.eof(e)
  File "C:\Python27\lib\site-packages\pexpect\expect.py", line 63, in eof
    raise EOF(msg)
pexpect.exceptions.EOF: End Of File (EOF).
<pexpect.popen_spawn.PopenSpawn object at 0x00000000033E9E80>
searcher: searcher_re:
    0: re.compile('msh')`

**Comment by raczben** [comment]
You should try [wexpect](https://pypi.org/project/wexpect/)

```
pip install wexpect
```

```python
import wexpect

child = wexpect.spawn('cmd.exe')
child.expect('>')
child.sendline('ls')
child.expect('>')
print(child.before)
```
