### ISSUE TITLE
async on windows raises NotImplementedError

### ISSUE THREAD

**Issue by pbartyik** [pexpect/pexpect#548]
\venv\lib\site-packages\pexpect\_async.py", line 20, in expect_async
    .connect_read_pipe(lambda: pw, expecter.spawn)
  \Python\Python36-32\Lib\asyncio\base_events.py", line 1098, in connect_read_pipe
    transport = self._make_read_pipe_transport(pipe, protocol, waiter)
  \Python\Python36-32\Lib\asyncio\base_events.py", line 328, in _make_read_pipe_transport
    raise NotImplementedError

Pexpect was called as such:
response = await child.expect([
                   'a','b','c'
                ], async_ = True)

python version is 3.6.3
pexpect version is 4.4.0

Might have something to do with this: https://stackoverflow.com/questions/31510190/aysncio-cannot-read-stdin-on-windows

**Comment by takluyver** [comment]
As that SO question suggests, you could try the ProactorEventLoop. A lot of unix-y functionality for file descriptors is only available for sockets on Windows, so I don't know what works.

**Comment by pbartyik** [comment]
upgraded to 4.6.0, tried ProactorEventLoop, didn't help.

ERROR:asyncio:Fatal read error on pipe transport
protocol: <pexpect._async.PatternWaiter object at 0x039FF1D0>
transport: <_ProactorReadPipeTransport fd=-1>
Traceback (most recent call last):
  File "\Python\Python36-32\Lib\asyncio\proactor_events.py", line 202, in _loop_reading
    self._read_fut = self._loop._proactor.recv(self._sock, 4096)
  File "\Python\Python36-32\Lib\asyncio\windows_events.py", line 430, in recv
    self._register_with_iocp(conn)
  File "\Python\Python36-32\Lib\asyncio\windows_events.py", line 611, in _register_with_iocp
    _overlapped.CreateIoCompletionPort(obj.fileno(), self._iocp, 0, 0)
OSError: [WinError 87] The parameter is incorrect
ERROR:asyncio:Exception in callback _ProactorBasePipeTransport._call_connection_lost(OSError(22, '...one, 87, None))
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(OSError(22, '...one, 87, None))>
Traceback (most recent call last):
  File "\Python\Python36-32\Lib\asyncio\proactor_events.py", line 129, in _call_connection_lost
    self._protocol.connection_lost(exc)
  File "\venv\lib\site-packages\pexpect\_async.py", line 87, in connection_lost
    self.error(exc)
  File "\venv\lib\site-packages\pexpect\_async.py", line 48, in error
    self.transport.pause_reading()
  File "\Python\Python36-32\Lib\asyncio\proactor_events.py", line 163, in pause_reading
    raise RuntimeError('Cannot pause_reading() when closing')
RuntimeError: Cannot pause_reading() when closing

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "\Python\Python36-32\Lib\asyncio\events.py", line 127, in _run
    self._callback(*self._args)
  File "\Python\Python36-32\Lib\asyncio\proactor_events.py", line 137, in _call_connection_lost
    self._sock.close()
AttributeError: 'PopenSpawn' object has no attribute 'close'

**Comment by pbartyik** [comment]
Upgraded python to 3.7.2 (pexpect 4.6.0)
This time when spawning a plink session I get the following traceback. Any help is welcome.

> Fatal read error on pipe transport
> protocol: <pexpect._async.PatternWaiter object at 0x03AC8810>
> transport: <_ProactorReadPipeTransport fd=-1>
> Traceback (most recent call last):
>   File "C:\Python\Python37-32\Lib\asyncio\proactor_events.py", line 274, in _loop_reading
>     self._read_fut = self._loop._proactor.recv(self._sock, 32768)
>   File "C:\Python\Python37-32\Lib\asyncio\windows_events.py", line 416, in recv
>     self._register_with_iocp(conn)
>   File "C:\Python\Python37-32\Lib\asyncio\windows_events.py", line 641, in _register_with_iocp
>     _overlapped.CreateIoCompletionPort(obj.fileno(), self._iocp, 0, 0)
> OSError: [WinError 87] The parameter is incorrect
> ERROR:asyncio:Exception in callback _ProactorReadPipeTransport._loop_reading()
> handle: <Handle _ProactorReadPipeTransport._loop_reading()>
> Traceback (most recent call last):
>   File "C:\Python\Python37-32\Lib\asyncio\proactor_events.py", line 274, in _loop_reading
>     self._read_fut = self._loop._proactor.recv(self._sock, 32768)
>   File "C:\Python\Python37-32\Lib\asyncio\windows_events.py", line 416, in recv
>     self._register_with_iocp(conn)
>   File "C:\Python\Python37-32\Lib\asyncio\windows_events.py", line 641, in _register_with_iocp
>     _overlapped.CreateIoCompletionPort(obj.fileno(), self._iocp, 0, 0)
> OSError: [WinError 87] The parameter is incorrect
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Python\Python37-32\Lib\asyncio\events.py", line 88, in _run
>     self._context.run(self._callback, *self._args)
>   File "C:\Python\Python37-32\Lib\asyncio\proactor_events.py", line 284, in _loop_reading
>     self._fatal_error(exc, 'Fatal read error on pipe transport')
>   File "C:\Python\Python37-32\Lib\asyncio\proactor_events.py", line 110, in _fatal_error
>     self._force_close(exc)
>   File "C:\Python\Python37-32\Lib\asyncio\proactor_events.py", line 113, in _force_close
>     if self._empty_waiter is not None:
> AttributeError: '_ProactorReadPipeTransport' object has no attribute '_empty_waiter'
