### ISSUE TITLE
Expect raises `TypeError` in Python 3 if patterns include RegExp compiled from a non-bytes type string

### ISSUE THREAD

**Issue by EmersonPrado** [pexpect/pexpect#558]
> From commit `03168dd3cb57cbafebccef0d46e00c6bbd4bb0b9`
> Python 3.6.7-1~18.04 in Ubuntu 18.04

Docs say Pexpect accepts compiled regular expressions as patterns:

```Shell
pydoc3 pexpect.spawn.compile_pattern_list	# Idem for pexpect.spawnbase
"Patterns must be a StringType, EOF, TIMEOUT, SRE_Pattern, or a list of those"
pydoc3 pexpect.spawn.expect			# Idem for pexpect.spawnbase
"The pattern can be a StringType, EOF, a compiled re, or a list of any of those types"
pydoc3 pexpect.spawn.expect_list		# Idem for pexpect.spawnbase
"This takes a list of compiled regular expressions"
pydoc3 pexpect.expect.searcher_re.__init__
"'patterns' may be a list or other sequence of compiled regular expressions"
```

But, if we do provide a pattern with compiled RegExp, class `expect.search` raises exception `TypeError` in line 294 (`match = s.search(buffer, searchstart)`)

```Python
>>> from re import compile as re_compile
>>> from lib.pexpect.pexpect import spawn, EOF, TIMEOUT
>>>
>>> spawn_object = spawn('ls')
>>> spawn_object.expect([re_compile(': '), EOF, TIMEOUT])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<Pexpect clone>/pexpect/spawnbase.py", line 341, in expect
    timeout, searchwindowsize, async_)
  File "<Pexpect clone>/pexpect/spawnbase.py", line 369, in expect_list
    return exp.expect_loop(timeout)
  File "<Pexpect clone>/pexpect/expect.py", line 103, in expect_loop
    idx = self.new_data(incoming)
  File "<Pexpect clone>/pexpect/expect.py", line 29, in new_data
    index = searcher.search(window, len(data))
  File "<Pexpect clone>/pexpect/expect.py", line 294, in search
    match = s.search(buffer, searchstart)
TypeError: cannot use a string pattern on a bytes-like object
>>>
```

Pexpect parses and searches correctly a string pattern, or a RegExp pattern compiled from a bytes-type string

```Python
>>> from re import compile as re_compile
>>> from lib.pexpect.pexpect import spawn, EOF, TIMEOUT
>>>
>>> spawn_object = spawn('ls')
>>> spawn_object.expect([': ', EOF, TIMEOUT])
1
>>> spawn_object = spawn('ls')
>>> spawn_object.expect([re_compile(b': '), EOF, TIMEOUT])
1
>>>
```

Either `Pexpect.expect` should handle all compiled RegExps, or the docs should state which RegExps are compatible

**Comment by EmersonPrado** [comment]
Some debugging

- Class [`SpawnBase`](https://github.com/pexpect/pexpect/blob/master/pexpect/spawnbase.py) takes encoding as an argument and selects encoders, decoders and types from it

```Python
class SpawnBase(object):
    ...
    def __init__(self, timeout=30, maxread=2000, searchwindowsize=None,
                 logfile=None, encoding=None, codec_errors='strict'):
        if encoding is None:
            # bytes mode (accepts some unicode for backwards compatibility)
            self._encoder = self._decoder = _NullCoder()
            self.string_type = bytes
            ...
            if PY3:
                self.allowed_string_types = (bytes, str)
                ...
        else:
            # unicode mode
            self._encoder = codecs.getincrementalencoder(encoding)(codec_errors)
            self._decoder = codecs.getincrementaldecoder(encoding)(codec_errors)
            self.string_type = text_type
            ...
            self.allowed_string_types = (text_type, )
```


- If encoding is not specified, function [`SpawnBase._coerce_expect_string`](https://github.com/pexpect/pexpect/blob/master/pexpect/spawnbase.py#L136) forces expect string to "bytes" type

```Python
    def _coerce_expect_string(self, s):
        if self.encoding is None and not isinstance(s, bytes):
            return s.encode('ascii')
        return s
```

- Any `encode` changes string type to 'bytes'

```Python
>>> type('')
<class 'str'>
>>> type(''.encode('ascii'))
<class 'bytes'>
>>> type(''.encode('utf-8'))
<class 'bytes'>
```


- Function [`SpawnBase.compile_pattern_list`](https://github.com/pexpect/pexpect/blob/master/pexpect/spawnbase.py#L192) , when parsing the pattern list:
  - Converts strings to "bytes" type and compiles them as RegExps
  - Leaves compiled RegExps untouched, possibly compiled from non-"bytes" type strings

```Python
        for idx, p in enumerate(patterns):
            if isinstance(p, self.allowed_string_types):
                p = self._coerce_expect_string(p)
                compiled_pattern_list.append(re.compile(p, compile_flags))
            ...
            elif isinstance(p, type(re.compile(''))):
                compiled_pattern_list.append(p)
            ...
        return compiled_pattern_list
```

- For instance, `type` does not differentiate compiled RegExps from different string types

```Python
>>> type(re_compile(b'')) == type(re_compile(''))
True
>>> type(re_compile(r'')) == type(re_compile(''))
True
```


- Function [`expect.searcher_re.search`](https://github.com/pexpect/pexpect/blob/master/pexpect/expect.py#L275) doesn't seem to cope with RegExps compiled from non-"bytes" type strings

```Python
        for index, s in self._searches:
            print('Search: {}\tType: {}'.format(s, type(s)))	# Included to show object received by function
            match = s.search(buffer, searchstart)
```


- Preparing for test

```Python
>>> from re import compile as re_compile
>>> from lib.pexpect.pexpect import spawn, EOF, TIMEOUT
```

- When pattern includes strings of whatever type or encoding, **or a RegExp compiled from a bytes type string**, it compiles and parses without problems

```Python
>>> spawn_object = spawn('ls')
>>> spawn_object.expect([': ', EOF, TIMEOUT])
Search: re.compile(b': ', re.DOTALL)	Type: <class '_sre.SRE_Pattern'>
Search: re.compile(b': ', re.DOTALL)	Type: <class '_sre.SRE_Pattern'>
1
>>>
>>> spawn_object = spawn('ls')
>>> spawn_object.expect([b': ', EOF, TIMEOUT])
Search: re.compile(b': ', re.DOTALL)	Type: <class '_sre.SRE_Pattern'>
Search: re.compile(b': ', re.DOTALL)	Type: <class '_sre.SRE_Pattern'>
1
>>>
>>> spawn_object = spawn('ls')
>>> spawn_object.expect([r': ', EOF, TIMEOUT])
Search: re.compile(b': ', re.DOTALL)	Type: <class '_sre.SRE_Pattern'>
Search: re.compile(b': ', re.DOTALL)	Type: <class '_sre.SRE_Pattern'>
1
>>>
>>> spawn_object = spawn('ls')
>>> spawn_object.expect([re_compile(b': '), EOF, TIMEOUT])
Search: re.compile(b': ')	Type: <class '_sre.SRE_Pattern'>
Search: re.compile(b': ')	Type: <class '_sre.SRE_Pattern'>
1
```

- When pattern includes a RegExp compiled from a non-bytes type string, it raises a TypeError

```Python
>>> spawn_object = spawn('ls')
>>> spawn_object.expect([re_compile(': '), EOF, TIMEOUT])
Search: re.compile(': ')	Type: <class '_sre.SRE_Pattern'>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<Pexpect clone>/pexpect/spawnbase.py", line 341, in expect
    timeout, searchwindowsize, async_)
  File "<Pexpect clone>/pexpect/spawnbase.py", line 369, in expect_list
    return exp.expect_loop(timeout)
  File "<Pexpect clone>/pexpect/expect.py", line 103, in expect_loop
    idx = self.new_data(incoming)
  File "<Pexpect clone>/pexpect/expect.py", line 29, in new_data
    index = searcher.search(window, len(data))
  File "<Pexpect clone>/pexpect/expect.py", line 294, in search
    match = s.search(buffer, searchstart)
TypeError: cannot use a string pattern on a bytes-like object

>>> spawn_object = spawn('ls')
>>> spawn_object.expect([re_compile(r': '), EOF, TIMEOUT])
Search: re.compile(': ')	Type: <class '_sre.SRE_Pattern'>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<Pexpect clone>/pexpect/spawnbase.py", line 341, in expect
    timeout, searchwindowsize, async_)
  File "<Pexpect clone>/pexpect/spawnbase.py", line 369, in expect_list
    return exp.expect_loop(timeout)
  File "<Pexpect clone>/pexpect/expect.py", line 103, in expect_loop
    idx = self.new_data(incoming)
  File "<Pexpect clone>/pexpect/expect.py", line 29, in new_data
    index = searcher.search(window, len(data))
  File "<Pexpect clone>/pexpect/expect.py", line 294, in search
    match = s.search(buffer, searchstart)
TypeError: cannot use a string pattern on a bytes-like object
```

- When spawn receives an encoding argument, previously failed RegExp works

```Python
>>> spawn_object = spawn('ls', encoding='utf-8')
>>> spawn_object.expect([re_compile(': '), EOF, TIMEOUT])
Search: re.compile(': ')	Type: <class '_sre.SRE_Pattern'>
Search: re.compile(': ')	Type: <class '_sre.SRE_Pattern'>
1
>>> spawn_object = spawn('ls', encoding='ascii')
>>> spawn_object.expect([re_compile(': '), EOF, TIMEOUT])
Search: re.compile(': ')	Type: <class '_sre.SRE_Pattern'>
Search: re.compile(': ')	Type: <class '_sre.SRE_Pattern'>
>>> spawn_object = spawn('ls', encoding='utf-8')
>>> spawn_object.expect([re_compile(r': '), EOF, TIMEOUT])
Search: re.compile(': ')	Type: <class '_sre.SRE_Pattern'>
Search: re.compile(': ')	Type: <class '_sre.SRE_Pattern'>
1
>>> spawn_object = spawn('ls', encoding='ascii')
>>> spawn_object.expect([re_compile(r': '), EOF, TIMEOUT])
Search: re.compile(': ')	Type: <class '_sre.SRE_Pattern'>
Search: re.compile(': ')	Type: <class '_sre.SRE_Pattern'>
```

- Out of curiosity: spawn with encoding argument causes previously working RegExps to raise the opposite error

```Python
>>> spawn_object = spawn('ls', encoding='utf-8')
>>> spawn_object.expect([re_compile(b': '), EOF, TIMEOUT])
Search: re.compile(b': ')	Type: <class '_sre.SRE_Pattern'>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<Pexpect clone>/pexpect/spawnbase.py", line 341, in expect
    timeout, searchwindowsize, async_)
  File "<Pexpect clone>/pexpect/spawnbase.py", line 369, in expect_list
    return exp.expect_loop(timeout)
  File "<Pexpect clone>/pexpect/expect.py", line 103, in expect_loop
    idx = self.new_data(incoming)
  File "<Pexpect clone>/pexpect/expect.py", line 29, in new_data
    index = searcher.search(window, len(data))
  File "<Pexpect clone>/pexpect/expect.py", line 294, in search
    match = s.search(buffer, searchstart)
TypeError: cannot use a bytes pattern on a string-like object
>>> spawn_object = spawn('ls', encoding='ascii')
>>> spawn_object.expect([re_compile(b': '), EOF, TIMEOUT])
Search: re.compile(b': ')	Type: <class '_sre.SRE_Pattern'>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<Pexpect clone>/pexpect/spawnbase.py", line 341, in expect
    timeout, searchwindowsize, async_)
  File "<Pexpect clone>/pexpect/spawnbase.py", line 369, in expect_list
    return exp.expect_loop(timeout)
  File "<Pexpect clone>/pexpect/expect.py", line 103, in expect_loop
    idx = self.new_data(incoming)
  File "<Pexpect clone>/pexpect/expect.py", line 29, in new_data
    index = searcher.search(window, len(data))
  File "<Pexpect clone>/pexpect/expect.py", line 294, in search
    match = s.search(buffer, searchstart)
TypeError: cannot use a bytes pattern on a string-like object
```

**Comment by EmersonPrado** [comment]
Unfortunately, I can't imagine a way to coerce an already compiled RegExp to a bytes-type source, neither how to mess with `pexpect.expect.search` function

**Comment by EmersonPrado** [comment]
In fact, coercing is quite easy: the compiled regex object has the attribute `pattern`, so we just have to recreate the object from this pattern with the correct encoding. Sent [PR 559](https://github.com/pexpect/pexpect/pull/559) with a fix which works in Python 2 and 3, with consistent and coherent results.
The change reduced test coverage. If I learn how to test this part, I'll push new tests.

**Comment by EmersonPrado** [comment]
I wrote unit and integration tests, which failed before fix and passed afterwards, both in Python 2 and 3. But I messed the PR history so much I decided to open a new one. Pls now refer to [PR 560](https://github.com/pexpect/pexpect/pull/560).

**Comment by krichter722** [comment]
Could you take a look at this @takluyver, please. Usage of an important feature with Python3 is blocked.
