### ISSUE TITLE
pexpect.spawn() should not unconditionally encode arguments when encoding is set

### ISSUE THREAD

**Issue by intelfx** [pexpect/pexpect#564]
I'm trying to use pexpect to interact with a broken CLI program that hardcodes UTF-16 as its encoding. This fails because I cannot call `pexpect.spawn(..., encoding='utf-16', ...)`:

```
root@test-neo-debug-8f4ffb4cb-fq5fs:/neo-cli# /scripts/cli-create-wallet.py
/scripts/cli-create-wallet.py: DEBUG: wallet basedir: /neo-data
/scripts/cli-create-wallet.py: DEBUG: wallet path: /neo-data/wallet.json
/scripts/cli-create-wallet.py: DEBUG: wallet password: 0
Traceback (most recent call last):
  File "/scripts/cli-create-wallet.py", line 53, in <module>
    c = pexpect.spawn('dotnet', [ 'neo-cli.dll' ], encoding='utf_16_le', env={ 'TERM': 'dumb' })
  File "/usr/local/lib/python3.6/dist-packages/pexpect/pty_spawn.py", line 204, in __init__
    self._spawn(command, args, preexec_fn, dimensions)
  File "/usr/local/lib/python3.6/dist-packages/pexpect/pty_spawn.py", line 303, in _spawn
    cwd=self.cwd, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pexpect/pty_spawn.py", line 314, in _spawnpty
    return ptyprocess.PtyProcess.spawn(args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/ptyprocess/ptyprocess.py", line 209, in spawn
    command_with_path = which(command)
  File "/usr/lib/python3.6/shutil.py", line 1114, in which
    if _access_check(cmd, mode):
  File "/usr/lib/python3.6/shutil.py", line 1107, in _access_check
    return (os.path.exists(fn) and os.access(fn, mode)
  File "/usr/lib/python3.6/genericpath.py", line 19, in exists
    os.stat(path)
ValueError: stat: embedded null character in path
```

It appears from code that pexpect will skip encoding if you pass command line as bytes, but it does not work because apparently pexpect was not made with this usecase in mind (it breaks in all kinds of ways when it gets bytes for command line in python3).

Why does pexpect ever try to use `encoding` to encode the command line? Or, better, why there's a need to mangle the command line at all? Python's builtin `subprocess` module does not appear to do this (it is able to run processes just fine regardless of `encoding` you specify) and still works fine. What am I missing?

**Comment by dothque** [comment]
I am experiencing the same problem. Since I updated to osx 10.14 python hangs when I use spawn.
Example: `pexpect.spawn('ls', ['-latr', '/tmp']), encoding='latin-1')`
