### ISSUE TITLE
pexpect Does not find label that is sent getpass field

### ISSUE THREAD

**Issue by wolf002** [pexpect/pexpect#624]
I need to be authorized in another python script

The script code in which you need to log in

    import getpass
    import time
    time.sleep(1)
    login = input('Please enter your login: ')
    print('login '+login)
    time.sleep(1)
    code = input('Please enter the code you received: ')
    print('code '+code)
    time.sleep(1)
    password = getpass.getpass('Please enter your password: ')
    print('password '+password)
    print('Signed in successfully as '+login)

Authentication Automation Script Code

    import pexpect
    from pexpect import popen_spawn
    import time
    import sys
    
    login = 'nickname'
    code = '12345'
    password = 'secret'
    command = "python auth.py"
    print(command)
    child = pexpect.popen_spawn.PopenSpawn(command)
    child.logfile = sys.stdout.buffer
    #enter login
    try:
        child.expect('Please enter your login: ')  
    except pexpect.exceptions.TIMEOUT:
        print('Already auth')
        sys.exit()
    child.sendline(login)
    #enter code
    child.expect('Please enter the code you received: ')
    child.sendline(code)
    #enter password
    child.expect('Please enter your password: ')
    child.sendline(password)
    
    i = child.expect(['Signed in successfully.*',])
    if i==0:
        print('success Signed')

Automation script output
<pre>
    python auth.py
    Please enter your login: nickname
    login nickname
    Please enter the code you received: 12345
    Please enter your password: Traceback (most recent call last):
      File ".\check.py", line 24, in <module>
        child.expect('Please enter your password: ')
      File "C:\Users\Telnet\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pexpect\spawnbase.py", line 343, in expect
        return self.expect_list(compiled_pattern_list,
      File "C:\Users\Telnet\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pexpect\spawnbase.py", line 372, in expect_list
        return exp.expect_loop(timeout)
      File "C:\Users\Telnet\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pexpect\expect.py", line 181, in expect_loop
        return self.timeout(e)
      File "C:\Users\Telnet\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pexpect\expect.py", line 144, in timeout
        raise exc
    pexpect.exceptions.TIMEOUT: <pexpect.popen_spawn.PopenSpawn object at 0x0162E718>
    searcher: searcher_re:
        0: re.compile(b'Please enter your password: ')
    <pexpect.popen_spawn.PopenSpawn object at 0x0162E718>
    searcher: searcher_re:
        0: re.compile(b'Please enter your password: ')
</pre>
As seen child.expect('Please enter your password: ') not working

Tell me what I'm doing wrong?

**Comment by takluyver** [comment]
Educated guesswork, but it's probably a limitation of PopenSpawn: getpass probably bypasses the pipes Popen uses. Try [wexpect](https://pypi.org/project/wexpect/#description) as a Windows alternative.
