### ISSUE TITLE
Unable to reset expired password.  

### ISSUE THREAD

**Issue by mrniranjan** [pexpect/pexpect#628]
I have an environment(IPA) where when the user is created with initial password, the password expires during first login prompting for user to change password.  I am trying to change password using pxssh i get the below error:
```

[root@server1 ~]# python3 expect.py 
<class '__main__.pexpect_ssh'>
Password: ChangeThat@123

Password expired. Change your password now.
Current Password: ChangeThat@123
Traceback (most recent call last):
  File "expect.py", line 33, in login
    i = self.ssh.login(self.hostname, self.username, self.password, self.port)
  File "/usr/lib/python3.6/site-packages/pexpect/pxssh.py", line 313, in login
    raise ExceptionPxssh('password refused')
pexpect.pxssh.ExceptionPxssh: password refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "expect.py", line 112, in <module>
    client.login(reset=True, new_password='Secret123')
  File "expect.py", line 42, in login
    self.ssh.sendline(self.password)
  File "/usr/lib/python3.6/site-packages/pexpect/pty_spawn.py", line 539, in sendline
    return self.send(s + self.linesep)
  File "/usr/lib/python3.6/site-packages/pexpect/pty_spawn.py", line 530, in send
    return os.write(self.child_fd, b)
OSError: [Errno 9] Bad file descriptor

```
The code is as below:
```
class pexpect_ssh(object):
    """ pexpect methods """
    def __init__(self, hostname, username,
                 password=None, port=None,
                 encoding='utf-8', debug=False):
        """ Initilized defaults """
        self.hostname = hostname
        self.username = username
        self.password = password
        self.encoding = encoding
        if port is None:
            self.port = 22
        else:
            self.port = port
        self.ssh_options = {'StrictHostKeyChecking': 'no',
                            'UserKnownHostsFile': '/dev/null'}
        self.ssh = pxssh.pxssh(options=self.ssh_options)
        if debug:
            self.ssh.logfile = sys.stdout.buffer

    def login(self, reset=False, new_password=None):
        """ login to host """
        #self.PROMPT = r"\[PEXPECT\][\$\#] "
        if reset:
            try:
                i = self.ssh.login(self.hostname, self.username, self.password, self.port)
                print("i = ", i)
                self.ssh.expect('Password:')
                self.ssh.sendline(self.password)
            except pexpect.pxssh.ExceptionPxssh as e:
                self.ssh.sendline(self.password)
                self.ssh.expect('New password:')
                self.ssh.sendline(new_password)
        else:
            try:
                self.ssh.login(self.hostname, self.username,
                               self.password, port=self.port)
            except pexpect.pxssh.ExceptionPxssh:
                raise Exception("%s Failed to login" % self.username)


client = pexpect_ssh('server1.testrealm.test', 'foobar0', ' ChangeThat@123', debug=True)
client.login(reset=True, new_password='Secret123')
```

**Comment by mrniranjan** [comment]
I am using python3-pexpect-4.3.1-3.el8.noarch

**Comment by Red-M** [comment]
If you're interested in using python to automate SSH, I strongly suggest not using pexpect and instead using either paramiko or RedSSH (which is my own library)(as per the note in pxssh's documentation [here](https://pexpect.readthedocs.io/en/stable/api/pxssh.html#pxssh-control-an-ssh-session)) to do so. However, if you insist on using pxssh, the first password prompt is handled by pxssh itself.

Firstly, you'll only ever get a `1` or `True` back from `self.ssh.login(self.hostname, self.username, self.password, self.port)` otherwise you'll get an exception.
However, I'm 99% sure that you're getting stuck because when the `'New password:'` comes up it matches [the password regex that pxssh uses to see the password prompt](https://github.com/pexpect/pexpect/blob/master/pexpect/pxssh.py#L434-L440), because of this the session is closed out and your attempts after the fact are basically just dropped and ignored.

If you're still interested in using pxssh I also recommend updating the version of pexpect you're using by installing via pip as 4.3 is rather old and our current stable is 4.8.

**Comment by mrniranjan** [comment]
@Red-M  Thanks for the reply. I will try the latest version and also other options that you have mentioned.
