### ISSUE TITLE
AttributeError: module 'pexpect' has no attribute 'spawn'

### ISSUE THREAD

**Issue by yasaminLG** [pexpect/pexpect#651]
i'm practicing some codes on Spyder(python 3.7) and when I do pexpect.spawn('ping -c 7 localhost'), I get the above error.

Does anyone know how to fix this?

**Comment by Red-M** [comment]
Please see #567 and #166.

**Comment by Wleroy280** [comment]
C:\Users\willy\PycharmProjects\TryExcept\venv\Scripts\python.exe C:/Users/willy/PycharmProjects/TryExcept/main.py
Traceback (most recent call last):
  File "C:\Users\willy\PycharmProjects\TryExcept\main.py", line 51, in <module>
    main()
  File "C:\Users\willy\PycharmProjects\TryExcept\main.py", line 46, in main
    child = connect(user, host, password)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\willy\PycharmProjects\TryExcept\main.py", line 18, in connect
    child = pexpect.spawn(connStr)
            ^^^^^^^^^^^^^
AttributeError: module 'pexpect' has no attribute 'spawn'

Process finished with exit code 1
