### ISSUE TITLE
PXSSH and custom pexpect login fails with EOF Exception

### ISSUE THREAD

**Issue by satyaprakash-1729** [pexpect/pexpect#694]
I am working on a tool which connects to a device via SSH multiple times and performs some tests. The workflow is basically connect to device -> do something -> disconnect -> connect again if required -> do something -> disconnect. The pxssh login method connects without any problem the first time but fails to connect the second time with EOF Exception. Something to note is that the client does receive the password prompt but after the password is supplied the connection returns EOF. I also wrote a custom login which extends pxssh login to eat up any EOF received during login but this method also didn't work as it keeps receiving EOF.

```
class MyPXSSH(pxssh.pxssh):
    def __init__(self, *args, **kwargs):
        super(MyPXSSH, self).__init__(*args, **kwargs)
    def login(self, server, username=None, password='', terminal_type='ansi',
              original_prompt=r"[#$]", login_timeout=10, port=None,
              auto_prompt_reset=True, ssh_key=None, quiet=True,
              sync_multiplier=1, check_local_ip=True,
              password_regex=r'(?i)(?:password:)|(?:passphrase for key)',
              ssh_tunnels={}, spawn_local_ssh=True,
              sync_original_prompt=True, ssh_config=None, cmd='ssh'):
        cmd += " -o'NoHostAuthenticationForLocalhost=yes' -p {} {}@{}".format(port, username, server)
        spawn._spawn(self, cmd)
        expect_array = ["(?i)are you sure you want to continue connecting", r"[#$]",
                        r'(?i)(?:password:)|(?:passphrase for key)', "(?i)permission denied",
                        TIMEOUT, "(?i)connection closed by remote host", EOF]
        i = self.expect(expect_array, timeout=5)
        retries = 5
        try:
            while i != 1 and retries > 0:
                log.info(">> STATE: {}".format(i))
                if i == 0:
                    self.sendline("yes")
                    i = self.expect(expect_array)
                elif i == 2:
                    self.sendline(password)
                    i = self.expect(expect_array)
                elif i == 6:
                    i = self.expect(expect_array)
                    retries -= 1
        except Exception as e:
            log.exception(e)
        if i != 1:
            self.close()
            raise ExceptionPxssh('Could not establish connection to host')
        # Following is same as pxssh login -----------------------------------
        if sync_original_prompt:
            if not self.sync_original_prompt(sync_multiplier):
                self.close()
                raise ExceptionPxssh('could not synchronize with original prompt')
        if auto_prompt_reset:
            if not self.set_unique_prompt():
                self.close()
                raise ExceptionPxssh('could not set shell prompt '
                                     '(received: %r, expected: %r).' % (
                                         self.before, self.PROMPT,))
        log.info("CONNECTED!")
        return True
```
This script prints the state of the session as -> 2 -> 6 -> 6 -> 6 ...... i.e. it receives password prompt but after that just keeps getting EOF. 

Note:
1. The code works without problem with pexpect == 4.2.0 + Python 2.7 but fails with pexpect == 4.8.0 + Python 3.8 & 3.9.
2. The OS is macOS Mojave.
3. The first time connection always connects the second time connection always fails.

Error Caught:

```
2021-06-25 15:45:34 - ERROR - Failed to connect. Retrying...
2021-06-25 15:45:34 - ERROR - End Of File (EOF). Empty string style platform.
<pexpect.pxssh.pxssh object at 0x127feb0a0>
command: /usr/bin/ssh
args: ['/usr/bin/ssh', '-q', '-oNoHostAuthenticationForLocalhost=yes', '-p', 'xxxxx', '-l', 'xxxxx', 'localhost']
buffer (last 100 chars): b''
before (last 100 chars): b' \r\n'
after: <class 'pexpect.exceptions.EOF'>
match: None
match_index: None
exitstatus: None
flag_eof: True
pid: 30020
child_fd: 26
closed: False
timeout: 60
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: <_io.BufferedWriter name='<stdout>'>
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile(b'(?i)are you sure you want to continue connecting')
    1: re.compile(b'[#$]')
    2: re.compile(b'(?i)(?:password:)|(?:passphrase for key)')
    3: re.compile(b'(?i)permission denied')
    4: re.compile(b'(?i)terminal type')
    5: TIMEOUT
Traceback (most recent call last):
  File "/src/helpers/utilities.py", line 590, in try_connect_ssh
    connection.make_connection(ipaddress=ipaddress, user=user,
  File "/src/transport/myssh.py", line 26, in make_connection
    self.ssh_process.login(ipaddress, user, password, port=port, sync_multiplier=5, check_local_ip=False)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pexpect/pxssh.py", line 418, in login
    i = self.expect(session_regex_array)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pexpect/spawnbase.py", line 343, in expect
    return self.expect_list(compiled_pattern_list,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pexpect/spawnbase.py", line 372, in expect_list
    return exp.expect_loop(timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pexpect/expect.py", line 179, in expect_loop
    return self.eof(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pexpect/expect.py", line 122, in eof
    raise exc
pexpect.exceptions.EOF: End Of File (EOF). Empty string style platform.
<pexpect.pxssh.pxssh object at 0x127feb0a0>
```

**Comment by Red-M** [comment]
That is because when you call [`pxssh.pxssh().logout()`](https://pexpect.readthedocs.io/en/stable/api/pxssh.html#pexpect.pxssh.pxssh.logout) the pty is closed and cannot be used again.
You'll either need to not call `pxssh.pxssh().logout()` or if you do still want to call `pxssh.pxssh().logout()` you can make a new pxssh object and use `pxssh.pxssh().login()` on that newly instanced object.
