### ISSUE TITLE
Why does `sendcontrol("c")` work while `sendcontrol("z")` does not?

### ISSUE THREAD

**Issue by emdash** [pexpect/pexpect#705]
I am trying use pexpect to test a unix shell in interactive mode, but not all control characters are generating the expected signals. I would like to understand the difference between `sendcontrol("c")` and `sendcontrol("z")`. The latter does not generate SIGSTOP as I would expect.

Here is a minimal example:

```
#! /usr/bin/python2

import pexpect
import os

SHELL = os.environ.get("TEST_SHELL", "bash")
TIMEOUT = int(os.environ.get("TEST_TIMEOUT", 2))
shell = pexpect.spawn(SHELL, timeout=TIMEOUT)
shell.expect(r".*\$")
shell.sendline("cat")
# works
shell.sendcontrol("c")
shell.expect(".*\$")

# does not work
shell.sendline("cat")
shell.sendcontrol("z")
shell.expect("\[1\]+ Stopped")
```

I would expect this to exit normally, instead it dies with `pexpect.exceptions.TIMEOUT`. The buffer contents contain `^Z`, which apparently was sent but not consumed.

```
$ ./pexpect_bug.py                                                                                                                      
Traceback (most recent call last):                                                                                                                             
  File "./pexpect_bug.py", line 19, in <module>                                                                                                                
    shell.expect("\[1\]+ Stopped")                                                                                                                             
  File "/usr/lib/python2.7/dist-packages/pexpect/spawnbase.py", line 341, in expect                                                                            
    timeout, searchwindowsize, async_)                                                                                                                         
  File "/usr/lib/python2.7/dist-packages/pexpect/spawnbase.py", line 369, in expect_list                                                                       
    return exp.expect_loop(timeout)                                                                                                                            
  File "/usr/lib/python2.7/dist-packages/pexpect/expect.py", line 119, in expect_loop                                                                          
    return self.timeout(e)                                                                                                                                     
  File "/usr/lib/python2.7/dist-packages/pexpect/expect.py", line 82, in timeout                                                                               
    raise TIMEOUT(msg)                                                                                                                                         
pexpect.exceptions.TIMEOUT: Timeout exceeded.                                                                                                                  
<pexpect.pty_spawn.spawn object at 0x7f9cc6cd1d90>                                                                                                             
command: /bin/bash                                                                                                                                             
args: ['/bin/bash']                                                                                                                                            
buffer (last 100 chars): ' ^Z'                                                                                                                                 
before (last 100 chars): ' ^Z'                                                                                                                                 
after: <class 'pexpect.exceptions.TIMEOUT'>                                                                                                                    
match: None                                                                                                                                                    
match_index: None                                                                                                                                              
exitstatus: None                                                                                                                                               
flag_eof: False                                                                                                                                                
pid: 9326                                                                                                                                                      
child_fd: 6                                                                                                                                                    
closed: False                                                                                                                                                  
timeout: 2                                                                                                                                                     
delimiter: <class 'pexpect.exceptions.EOF'>                                                                                                                    
logfile: None                                                                                                                                                  
logfile_read: None                                                                                                                                             
logfile_send: None                                                                                                                                             
maxread: 2000                                                                                                                                                  
ignorecase: False                                                                                                                                              
searchwindowsize: None                                                                                                                                         
delaybeforesend: 0.05                                                                                                                                          
delayafterclose: 0.1                                                                                                                                           
delayafterterminate: 0.1                                                                                                                                       
searcher: searcher_re:                                                                                                                                         
    0: re.compile('\\[1\\]+ Stopped')
```

**Comment by Red-M** [comment]
Try adding `^Z$` to your `shell.expect("\[1\]+ Stopped")`

**Comment by emdash** [comment]
A lot of time has passed. I'm not sure I have the context to understand exactly there the `^Z$` will appear in the output, and why this works.

**Comment by Red-M** [comment]
Apologies for the time delay.
That is because `^Z` will appear in the text sent back from the pty that is spawned, the `$` ensures that it is the end of a line.

**Comment by emdash** [comment]
I'm just curious what actually ends up printing ^Z? Is this the kernel? Or the shell process? Or the terminal emulator?

**Comment by Red-M** [comment]
The shell.

**Comment by Red-M** [comment]
Please re-open this if needed.
