### ISSUE TITLE
test failures when running tests in parallel with xdist

### ISSUE THREAD

**Issue by Apteryks** [pexpect/pexpect#809]
Hi,

Using pytest-xdist, the test suite is reduced from 163 s to 24 s on my system, but there are some new failures, probably due to resources contention:

```
___________________ ExpectTestCase.test_multiple_interrupts ____________________
[gw8] linux -- Python 3.10.7 /gnu/store/jjzbav1s0x8lqg1aal13irspwwblwdf4-python-wrapper-3.10.7/bin/python

self = <tests.test_socket_fd.ExpectTestCase testMethod=test_multiple_interrupts>

        def setUp(self):
            print(self.id())
            PexpectTestCase.PexpectTestCase.setUp(self)
            self.af = socket.AF_INET
            self.host = '127.0.0.1'
            try:
                socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            except socket.error:
                try:
                    socket.socket(socket.AF_INET6, socket.SOCK_STREAM)
                    self.af = socket.AF_INET6
                    self.host = '::1'
                except socket.error:
                    pass
            self.port = 49152 + 10000
            self.motd = b"""\
    ------------------------------------------------------------------------------
    *                  Welcome to the SOCKET UNIT TEST code!                     *
    ------------------------------------------------------------------------------
    *                                                                            *
    * This unit test code is our best effort at testing the ability of the       *
    * pexpect library to handle sockets. We need some text to test buffer size   *
    * handling.                                                                  *
    *                                                                            *
    * A page is 1024 bytes or 1K. 80 x 24 = 1920. So a standard terminal window  *
    * contains more than one page. We actually want more than a page for our     *
    * tests.                                                                     *
    *                                                                            *
    * This is the twelfth line, and we need 24. So we need a few more paragraphs.*
    * We can keep them short and just put lines between them.                    *
    *                                                                            *
    * The 80 x 24 terminal size comes from the ancient past when computers were  *
    * only able to display text in cuneiform writing.                            *
    *                                                                            *
    * The cunieform writing system used the edge of a reed to make marks on clay *
    * tablets.                                                                   *
    *                                                                            *
    * It was the forerunner of the style of handwriting used by doctors to write *
    * prescriptions. Thus the name: pre (before) script (writing) ion (charged   *
    * particle).                                                                 *
    ------------------------------------------------------------------------------
    """.replace(b'\n', b'\n\r') + b"\r\n"
            self.prompt1 = b'Press Return to continue:'
            self.prompt2 = b'Rate this unit test>'
            self.prompt3 = b'Press X to exit:'
            self.enter = b'\r\n'
            self.exit = b'X\r\n'
            self.server_up = multiprocessing.Event()
            self.server_process = multiprocessing.Process(target=self.socket_server, args=(self.server_up,))
            self.server_process.daemon = True
            self.server_process.start()
            counter = 0
            while not self.server_up.is_set():
                time.sleep(0.250)
                counter += 1
                if counter > (10 / 0.250):
>                   raise SocketServerError("Could not start socket server")
E                   tests.test_socket.SocketServerError: Could not start socket server

/tmp/guix-build-python-pexpect-4.9.0.drv-0/pexpect-4.9.0/tests/test_socket.py:95: SocketServerError
----------------------------- Captured stdout call -----------------------------
tests.test_socket_fd.ExpectTestCase.test_multiple_interrupts

 tests.test_socket_fd.ExpectTestCase.test_multiple_interrupts 
----------------------------- Captured stderr call -----------------------------
Process Process-2:
Traceback (most recent call last):
  File "/gnu/store/jjcka1g6sk2cvwx8nm4fdwpdq3vll0v0-python-3.10.7/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/gnu/store/jjcka1g6sk2cvwx8nm4fdwpdq3vll0v0-python-3.10.7/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/tmp/guix-build-python-pexpect-4.9.0.drv-0/pexpect-4.9.0/tests/test_socket.py", line 107, in socket_server
    sock.bind((self.host, self.port))
OSError: [Errno 98] Address already in use
____________________ ExpectTestCase.test_socket_with_write _____________________
[gw13] linux -- Python 3.10.7 /gnu/store/jjzbav1s0x8lqg1aal13irspwwblwdf4-python-wrapper-3.10.7/bin/python

self = <tests.test_socket_fd.ExpectTestCase testMethod=test_socket_with_write>

        def setUp(self):
            print(self.id())
            PexpectTestCase.PexpectTestCase.setUp(self)
            self.af = socket.AF_INET
            self.host = '127.0.0.1'
            try:
                socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            except socket.error:
                try:
                    socket.socket(socket.AF_INET6, socket.SOCK_STREAM)
                    self.af = socket.AF_INET6
                    self.host = '::1'
                except socket.error:
                    pass
            self.port = 49152 + 10000
            self.motd = b"""\
    ------------------------------------------------------------------------------
    *                  Welcome to the SOCKET UNIT TEST code!                     *
    ------------------------------------------------------------------------------
    *                                                                            *
    * This unit test code is our best effort at testing the ability of the       *
    * pexpect library to handle sockets. We need some text to test buffer size   *
    * handling.                                                                  *
    *                                                                            *
    * A page is 1024 bytes or 1K. 80 x 24 = 1920. So a standard terminal window  *
    * contains more than one page. We actually want more than a page for our     *
    * tests.                                                                     *
    *                                                                            *
    * This is the twelfth line, and we need 24. So we need a few more paragraphs.*
    * We can keep them short and just put lines between them.                    *
    *                                                                            *
    * The 80 x 24 terminal size comes from the ancient past when computers were  *
    * only able to display text in cuneiform writing.                            *
    *                                                                            *
    * The cunieform writing system used the edge of a reed to make marks on clay *
    * tablets.                                                                   *
    *                                                                            *
    * It was the forerunner of the style of handwriting used by doctors to write *
    * prescriptions. Thus the name: pre (before) script (writing) ion (charged   *
    * particle).                                                                 *
    ------------------------------------------------------------------------------
    """.replace(b'\n', b'\n\r') + b"\r\n"
            self.prompt1 = b'Press Return to continue:'
            self.prompt2 = b'Rate this unit test>'
            self.prompt3 = b'Press X to exit:'
            self.enter = b'\r\n'
            self.exit = b'X\r\n'
            self.server_up = multiprocessing.Event()
            self.server_process = multiprocessing.Process(target=self.socket_server, args=(self.server_up,))
            self.server_process.daemon = True
            self.server_process.start()
            counter = 0
            while not self.server_up.is_set():
                time.sleep(0.250)
                counter += 1
                if counter > (10 / 0.250):
>                   raise SocketServerError("Could not start socket server")
E                   tests.test_socket.SocketServerError: Could not start socket server

/tmp/guix-build-python-pexpect-4.9.0.drv-0/pexpect-4.9.0/tests/test_socket.py:95: SocketServerError
----------------------------- Captured stdout call -----------------------------
tests.test_socket_fd.ExpectTestCase.test_socket_with_write

 tests.test_socket_fd.ExpectTestCase.test_socket_with_write 
----------------------------- Captured stderr call -----------------------------
Process Process-2:
Traceback (most recent call last):
  File "/gnu/store/jjcka1g6sk2cvwx8nm4fdwpdq3vll0v0-python-3.10.7/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/gnu/store/jjcka1g6sk2cvwx8nm4fdwpdq3vll0v0-python-3.10.7/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/tmp/guix-build-python-pexpect-4.9.0.drv-0/pexpect-4.9.0/tests/test_socket.py", line 107, in socket_server
    sock.bind((self.host, self.port))
OSError: [Errno 98] Address already in use
=============================== warnings summary ===============================
pexpect/ANSI.py:29: 32 warnings
  /tmp/guix-build-python-pexpect-4.9.0.drv-0/pexpect-4.9.0/pexpect/ANSI.py:29: UserWarning: pexpect.screen and pexpect.ANSI are deprecated. We recommend using pyte to emulate a terminal screen: https://pypi.python.org/pypi/pyte
    from . import screen

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED tests/test_socket.py::ExpectTestCase::test_fd_isalive - tests.test_socket.SocketServerError: Could not start socket server
FAILED tests/test_socket.py::ExpectTestCase::test_fd_isatty - tests.test_socket.SocketServerError: Could not start socket server
FAILED tests/test_socket.py::ExpectTestCase::test_socket_with_write - tests.test_socket.SocketServerError: Could not start socket server
FAILED tests/test_socket_fd.py::ExpectTestCase::test_fd_isalive_poll - tests.test_socket.SocketServerError: Could not start socket server
FAILED tests/test_socket.py::ExpectTestCase::test_multiple_interrupts - tests.test_socket.SocketServerError: Could not start socket server
FAILED tests/test_socket_fd.py::ExpectTestCase::test_timeout - tests.test_socket.SocketServerError: Could not start socket server
FAILED tests/test_socket_fd.py::ExpectTestCase::test_fd_isalive - tests.test_socket.SocketServerError: Could not start socket server
FAILED tests/test_socket_fd.py::ExpectTestCase::test_fileobj - tests.test_socket.SocketServerError: Could not start socket server
FAILED tests/test_socket_fd.py::ExpectTestCase::test_fd_isatty - tests.test_socket.SocketServerError: Could not start socket server
FAILED tests/test_socket.py::ExpectTestCase::test_timeout - tests.test_socket.SocketServerError: Could not start socket server
FAILED tests/test_socket_fd.py::ExpectTestCase::test_not_int - tests.test_socket.SocketServerError: Could not start socket server
FAILED tests/test_socket.py::ExpectTestCase::test_maxread - tests.test_socket.SocketServerError: Could not start socket server
FAILED tests/test_socket.py::ExpectTestCase::test_fd_isalive_poll - tests.test_socket.SocketServerError: Could not start socket server
FAILED tests/test_socket.py::ExpectTestCase::test_socket - tests.test_socket.SocketServerError: Could not start socket server
FAILED tests/test_socket_fd.py::ExpectTestCase::test_fd_isatty_poll - tests.test_socket.SocketServerError: Could not start socket server
FAILED tests/test_socket_fd.py::ExpectTestCase::test_socket - tests.test_socket.SocketServerError: Could not start socket server
FAILED tests/test_socket_fd.py::ExpectTestCase::test_maxread - tests.test_socket.SocketServerError: Could not start socket server
FAILED tests/test_socket_fd.py::ExpectTestCase::test_multiple_interrupts - tests.test_socket.SocketServerError: Could not start socket server
FAILED tests/test_socket_fd.py::ExpectTestCase::test_socket_with_write - tests.test_socket.SocketServerError: Could not start socket server
================= 19 failed, 229 passed, 32 warnings in 24.16s =================
```

It'd be nice if the test suite was refactored to accommodate running tests in parallel.

**Comment by apteryks** [comment]
It still hapens:
```
=========================== short test summary info ============================
FAILED tests/test_socket.py::ExpectTestCase::test_maxread - tests.test_socket.SocketServerError: Could not start socket server
FAILED tests/test_socket.py::ExpectTestCase::test_socket - tests.test_socket.SocketServerError: Could not start socket server
FAILED tests/test_socket.py::ExpectTestCase::test_fd_isatty - tests.test_socket.SocketServerError: Could not start socket server
FAILED tests/test_socket.py::ExpectTestCase::test_timeout - tests.test_socket.SocketServerError: Could not start socket server
FAILED tests/test_socket_fd.py::ExpectTestCase::test_not_int - tests.test_socket.SocketServerError: Could not start socket server
FAILED tests/test_socket.py::ExpectTestCase::test_interrupt - tests.test_socket.SocketServerError: Could not start socket server
FAILED tests/test_socket_fd.py::ExpectTestCase::test_fd_isatty_poll - tests.test_socket.SocketServerError: Could not start socket server
FAILED tests/test_socket_fd.py::ExpectTestCase::test_fd_isalive_poll - tests.test_socket.SocketServerError: Could not start socket server
FAILED tests/test_socket_fd.py::ExpectTestCase::test_interrupt - tests.test_socket.SocketServerError: Could not start socket server
FAILED tests/test_socket_fd.py::ExpectTestCase::test_fileobj - tests.test_socket.SocketServerError: Could not start socket server
FAILED tests/test_socket_fd.py::ExpectTestCase::test_socket_with_write - tests.test_socket.SocketServerError: Could not start socket server
FAILED tests/test_socket.py::ExpectTestCase::test_multiple_interrupts - tests.test_socket.SocketServerError: Could not start socket server
FAILED tests/test_socket.py::ExpectTestCase::test_socket_with_write - tests.test_socket.SocketServerError: Could not start socket server
FAILED tests/test_socket_fd.py::ExpectTestCase::test_fd_isalive - tests.test_socket.SocketServerError: Could not start socket server
FAILED tests/test_socket.py::ExpectTestCase::test_fd_isatty_poll - tests.test_socket.SocketServerError: Could not start socket server
FAILED tests/test_socket_fd.py::ExpectTestCase::test_fd_isatty - tests.test_socket.SocketServerError: Could not start socket server
FAILED tests/test_socket_fd.py::ExpectTestCase::test_socket - tests.test_socket.SocketServerError: Could not start socket server
FAILED tests/test_socket_fd.py::ExpectTestCase::test_maxread - tests.test_socket.SocketServerError: Could not start socket server
FAILED tests/test_socket_fd.py::ExpectTestCase::test_timeout - tests.test_socket.SocketServerError: Could not start socket server
FAILED tests/test_socket_fd.py::ExpectTestCase::test_not_file_descriptor - tests.test_socket.SocketServerError: Could not start socket server
================= 20 failed, 228 passed, 32 warnings in 23.76s =================
```

Can be worked around by ignoring the socket tests with the pytest arguments:
```
              "--ignore=tests/test_socket.py"
              "--ignore=tests/test_socket_fd.py"
```

**Comment by apteryks** [comment]
Actually, even when when not using xdist to run tests in parallel, I'm not seeing `test_multiple_interrupts` hang very often.
